### ISSUE TITLE
Publish docs to GitHub pages

### ISSUE THREAD

**Issue by naim94a** [microsoft/winrt-rs#109]
As long as this crate isn't published on crates.io/docs.rs, it would be useful to have online documentation of the latest stable or master branch

**Comment by anggar-dhika** [comment]
Nah main yuk di Joker123gaming.co

**Comment by anggar-dhika** [comment]
Buat kamu cocok kalo main di Joker123gaming.co

**Comment by kennykerr** [comment]
Sorry for the delay. We should be ready to publish a preview release to crates.io/docs.rs soon.
