### ISSUE TITLE
Couldn't compile winmd_macros

### ISSUE THREAD

**Issue by AW14Saurabh** [microsoft/winrt-rs#120]
I am trying to compile the minesweeper example from the [blog post](https://blogs.windows.com/windowsdeveloper/2020/04/30/rust-winrt-public-preview/), and am getting the following error.

>error[E0432]: unresolved import \`proc_macro\`
> --> C:\Users\aw14s\.cargo\git\checkouts\winrt-rs-5b24704ba4b09dbb\837e0cb\crates\winmd\macros\src\lib.rs:1:5   
>  |
>1 | use proc_macro::TokenStream;
>  |     ^^^^^^^^^^ help: a similar path exists: \`syn::proc_macro\`
>
>error: aborting due to previous error
>
>For more information about this error, try \`rustc --explain E0432\`.
>error: could not compile \`winmd_macros\`.

**Comment by rylev** [comment]
This is most likely due to you using an old version of Rust. If you update Rust: `rustup update` do you still get the same error?

**Comment by AW14Saurabh** [comment]
oop my bad should have done that first. Thanks for the help!
