### ISSUE TITLE
Relation to winapi-rs

### ISSUE THREAD

**Issue by TomPridham** [microsoft/winrt-rs#126]
Hi, there is https://github.com/retep998/winapi-rs. Which has been around for a while. Is this library intended to supersede that one or are they complementary?

**Comment by robmikh** [comment]
The winapi crate is a community crate that provides bindings to various Win32 APIs and some COM APIs (like Direct3D).

This crate provides language bindings for Rust for the [Windows Runtime](https://en.wikipedia.org/wiki/Windows_Runtime). There are various system APIs that run this way, like the Windows.UI.Composition APIs. 

The two projects are fairly different, although you might use them together. For example, you may use RoInitialize defined in the winapi crate to initialize COM before using Rust/WinRT to activate various classes.
