### ISSUE TITLE
Document any support channels, even if unofficial

### ISSUE THREAD

**Issue by ndarilek** [microsoft/winrt-rs#134]
Hey folks, new to working with WinRT. I thought I'd attempt to use this library to add speech synthesis support to my [tts crate](https://gitlab.com/ndarilek/tts-rs).

First, are there any support channels? I recognize this is a public preview--I'm just having some struggles mapping API concepts to this binding. I hope I'm just missing something obvious.

Assuming there aren't any, here's what I'm struggling with. This is my quick-and-dirty adaptation of the speech synthesis examples from the docs:

```
#[cfg(windows)]

winrt::import!(
    dependencies
        "os"
    modules
        "windows.foundation"
        "windows.media.playback"
        "windows.media.speechsynthesis"
);

use log::{info, trace};
use windows::media::playback::MediaPlayer;
use windows::media::speech_synthesis::SpeechSynthesizer;
...

    fn speak(&self, text: &str, interrupt: bool) -> std::result::Result<(), Error> {
        trace!("speak({}, {})", text, interrupt);
        let stream = self
            .synth
            .synthesize_text_to_stream_async(text)
            .expect("Failed to create stream")
            .get_results()
            .expect("Failed to get results");
        self.player.set_uri_source(stream.get_absolute_uri());
        self.player.play();
        Ok(())
    }
...
```

Here are some of the errors I get:

```
error[E0369]: binary operation `==` cannot be applied to type `backends::winrt::windows::foundation::IReference<u64>`
  --> src\backends\winrt.rs:3:1
   |
3  | / winrt::import!(
4  | |     dependencies
5  | |         "os"
6  | |     modules
...  |
9  | |         "windows.media.speechsynthesis"
10 | | );
   | |__^
   |
   = note: an implementation of `std::cmp::PartialEq` might be missing for `backends::winrt::windows::foundation::IReference<u64>`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0369]: binary operation `!=` cannot be applied to type `backends::winrt::windows::foundation::IReference<u64>`
  --> src\backends\winrt.rs:3:1
   |
3  | / winrt::import!(
4  | |     dependencies
5  | |         "os"
6  | |     modules
...  |
9  | |         "windows.media.speechsynthesis"
10 | | );
   | |__^
   |
   = note: an implementation of `std::cmp::PartialEq` might be missing for `backends::winrt::windows::foundation::IReference<u64>`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `backends::winrt::windows::foundation::IReference<u64>` doesn't implement `std::fmt::Debug`
  --> src\backends\winrt.rs:3:1
   |
3  | / winrt::import!(
4  | |     dependencies
5  | |         "os"
6  | |     modules
...  |
9  | |         "windows.media.speechsynthesis"
10 | | );
   | |__^ `backends::winrt::windows::foundation::IReference<u64>` cannot be formatted using `{:?}`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `backends::winrt::windows::foundation::IReference<u64>`
   = note: add `#[derive(Debug)]` or manually implement `std::fmt::Debug`
   = note: required because of the requirements on the impl of `std::fmt::Debug` for `&backends::winrt::windows::foundation::IReference<u64>`
   = note: required for the cast to the object type `dyn std::fmt::Debug`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

What should I be doing here? To access `MediaPlayer` and other classes, do I reference "windows.media.playback" or should "windows.media" be enough? I'm not entirely clear what's going on here. Do I just camel-case the namespace references I find in the documentation for whatever class I'm referencing? I also assume I need to strip the leading "system."? But I'm not sure what I'm doing wrong.

```
error[E0599]: no method named `get_absolute_uri` found for struct `backends::winrt::windows::media::speech_synthesis::SpeechSynthesisStream` in the current scope
  --> src\backends\winrt.rs:51:43
   |
3  | / winrt::import!(
4  | |     dependencies
5  | |         "os"
6  | |     modules
...  |
9  | |         "windows.media.speechsynthesis"
10 | | );
   | |__- method `get_absolute_uri` not found for this
...
51 |           self.player.set_uri_source(stream.get_absolute_uri());
   |                                             ^^^^^^^^^^^^^^^^ method not found in `backends::winrt::windows::media::speech_synthesis::SpeechSynthesisStream`
```

Likewise, I'm not sure why these methods aren't found. I thought I saw them referenced in the docs. Do I need another import to pull these in? Rust-analyzer doesn't show many method suggestions, so I'm guessing so.

Thanks for any help.

**Comment by robmikh** [comment]
The error you have with `IReference<u64>` is probably related to #104 (and #131).

Generally, when you find the type you'd like to use in the docs (like on MSDN), you should import the namespace that type is found in. However, be careful that you're looking at the WinRT class and not something from WPF (there are some unfortunate name collisions). For example, if you find `MediaPlayer` on a page like this: https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.mediaplayer?view=netcore-3.1, it's probably not the one you want. The tell is usually the Windows namespace is missing and that there isn't any mention on the page of what Universal Contract version supports the type. This is the page you should look for: https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Playback.MediaPlayer?view=winrt-18362. Notice that it has a "Windows 10 requirements" section that has the contract version. Thus you should import the Windows.Media.Playback namespace.

As for your error with `get_absolute_uri`, I'm unable to find that function or property on the [`SpeechSynthesisStream`](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.SpeechSynthesis.SpeechSynthesisStream?redirectedfrom=MSDN&view=winrt-18362) page. In addition, if that is a WinRT property and not a method, the get method is usually just the property name. For example, for the [`Uri`](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Uri?view=winrt-18362) type there is an `AbsoluteUri` property. You should access it by calling `let my_absolute_uri = my_uri.absolute_uri()?`. Assignment uses the `set_` prefix.

**Comment by ndarilek** [comment]
Thanks, this is super helpful. I've only recently begun dipping a toe in 
the UWP/C# ecosystem, and it all seems way more overwhelming than just 
about anything else I work with. :) I'll keep these pointers in mind 
going forward.

**Comment by robmikh** [comment]
No problem! Welcome to the WinRT/UWP ecosystem! 🙂 

I'll close this issue for now, let us know if you run into anything else.

**Comment by kennykerr** [comment]
#137 fixes this issue. There may be other issues with using Windows.Media but at least you can start experimenting as the import should succeed/compile. Let me know how it goes.
