### ISSUE TITLE
error[E0599]: no function or associated item named `new` found for struct `backends::winrt::windows::media::playback::MediaPlaybackItem` in the current scope

### ISSUE THREAD

**Issue by ndarilek** [microsoft/winrt-rs#147]
Thanks for all the quick fixes in this library!

I'm attempting to use [MediaPlaybackItem](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Playback.MediaPlaybackItem?view=winrt-19041). Here's roughly what I have:

```
use winrt::*;

import!(
    dependencies
        os
    modules
        "windows.media.core"
        "windows.media.playback"
        "windows.media.speechsynthesis"
);

...
        let stream = self.synth.synthesize_text_to_stream_async(text)?.get()?;
        let content_type = stream.content_type()?;
        let source = MediaSource::create_from_stream(stream, content_type)?;
        let item = MediaPlaybackItem::new(source)?;
        self.player.set_source(item)?;
        Ok(())
```

Only, I get the error in the title. `MediaPlaybackItem` seems to have a constructor that accepts a source. I've been successfully assigning my source to a player, so I do seem to have one, and I'm not sure why this API call isn't resolving. I can provide a repro if needed, but am filing this in case I'm hitting some issue that already exists.

Thanks again.

**Comment by kennykerr** [comment]
The `new` function is reserved for the "constructor" without any arguments (called a default constructor in some languages). There is a static `create` method that accepts a `MediaSource`. You can try something like this:

```rust
let item = MediaPlaybackItem::create(source)?;
```

This should get easier once we have code completion tracked by #107.
