### ISSUE TITLE
Support for creating composable types

### ISSUE THREAD

**Issue by 06393993** [microsoft/winrt-rs#148]
Is it possible to use the [Xaml Island](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/using-the-xaml-hosting-api) with this crate in Rust?

It seems that it's very difficult to create the [DesktopWindowXamlSource](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.hosting.desktopwindowxamlsource?view=winrt-19041) class which is under a [ComposableAttribute](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.metadata.composableattribute?view=winrt-19041) and should be created via a factory class(IDesktopWindowXamlSourceFactory) which is undocumented.

If further efforts are planed to make, I am wondering if you could share any information on when that will be scheduled? Thanks.

**Comment by kennykerr** [comment]
Support for composable types (specifically deriving

**Comment by kennykerr** [comment]
It should be possible, although it is not simple. There are a few issues that need to be addressed before broader Xaml support becomes more feasible including #119 #92 #91 and #81

We're working hard at these remaining issues. It may still be some time, but the goal is to make procedural Xaml (at the very least) very simple with Rust.

**Comment by roblabla** [comment]
I've got a working XAML Island, see https://github.com/roblabla/ubuntu-installer

In particular the DesktopWindowXamlSource can be created with `winrt::factory`, see https://github.com/roblabla/ubuntu-installer/blob/master/src/main.rs#L33

**Comment by kennykerr** [comment]
Yes, once we're done you'll be able to use use something like this:

```rust
let source = DesktopWindowXamlSource::new()?;
```
