### ISSUE TITLE
Support reg-free activation

### ISSUE THREAD

**Issue by kennykerr** [microsoft/winrt-rs#158]
C++/WinRT offers registration-free activation so that WinRT components need not be registered in order to support activation from any desktop/console app. Rust/WinRT needs the same support to allow activation of 3rd party components outside of store apps.

**Comment by Alovchin91** [comment]
Is this about the feature that is supported starting 1903, or the support for older operating system versions (e.g. explicit `GetActivationFactory` calls)?

**Comment by kennykerr** [comment]
No, this is the support provided by C++/WinRT to support reg-free activation directly (rather than relying on external/OS support). You are still free to use the manifest support provided by Windows for reg-free activation where available. That should work without any specific support from Rust/WinRT.
