### ISSUE TITLE
Nuget example writes files outside OUT_DIR

### ISSUE THREAD

**Issue by roblabla** [microsoft/winrt-rs#159]
Currently, the example build.rs for nuget packages writes outside build.rs, as seen [here](https://github.com/microsoft/winrt-rs/blob/master/examples/nuget-dependency/build.rs#L4). This is a problem for two reason:

1. Build scripts should not write to any files outside OUT_DIR, as documented [here](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script). In fact, even stronger languaged is found in the [build script example](https://doc.rust-lang.org/cargo/reference/build-script-examples.html#code-generation), where it says:

    > In general, build scripts should not modify any files outside of OUT_DIR. It may seem fine on the first blush, but it does cause problems when you use such crate as a dependency, because there's an implicit invariant that sources in .cargo/registry should be immutable. cargo won't allow such scripts when packaging.

2. The script currently hardcodes the path to `target`, even though it's possible to relocate the target folder, see [build.target-dir](https://doc.rust-lang.org/cargo/reference/config.html#buildtarget-dir).

----------------

Unfortunately, I don't really have a simple solution. At the very least, the second problem can be addressed by using [`cargo_metadata`](https://docs.rs/cargo_metadata/0.9.1/cargo_metadata/) to find the target folder, instead of hardcoding the path [in the build.rs](https://github.com/microsoft/winrt-rs/blob/master/examples/nuget-dependency/build.rs) and [the import macro](https://github.com/microsoft/winrt-rs/blob/master/crates/macros/src/lib.rs#L182).

In fact, cargo metadata is already used in the import macro, but it looks for the workspace root instead of using the `target_path`.

-------------------

EDIT: Further experimenting showed that the following approach won't work, as `rustc-env` in dependencies won't be propagated to the main crate, and so the `import` macro won't see it.

For the first point (avoiding writing to OUT_DIR), I thought a bit about the potential solutions, and here's the cleanest one I could think of: Use [`cargo.rustc-env`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-envvarvalue) to create an environment variable per `winmd` file, specifying the path where it can be found. E.G.

```rust
fn main() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let src = current.join("nuget");
    for item in std::fs::read_dir(src) {
        println!("cargo:rustc-env=NUGET_DEP_{}={}", item.unwrap().file_name().into_string().unwrap(), out_dir);
    }
}
```

The [nuget path resolver](https://github.com/microsoft/winrt-rs/blob/master/crates/macros/src/lib.rs#L182) would then use `std::env::var("NUGET_DEP_{}")` to find where the winmd is. This could all be abstracted away behind a `dep-dependency` to simplify the implementation.

**Comment by rylev** [comment]
Fixed by #154
