### ISSUE TITLE
Nuget support needs special handling for SDK nuget package

### ISSUE THREAD

**Issue by kennykerr** [microsoft/winrt-rs#165]

**Comment by rylev** [comment]
So I believe this is not an issue for winrt-rs, but rather for cargo nuget. Cargo nuget should ensure that it knows how to find the Winmd files and the DLLs, but winrt-rs should always assume it can find them in one place.

**Comment by kennykerr** [comment]
Should cargo nuget be part of https://github.com/microsoft/winrt-rs somehow?

**Comment by rylev** [comment]
Yes I think it should be. I can move it over
