### ISSUE TITLE
Reduce friction between ComInterface and RuntimeType

### ISSUE THREAD

**Issue by kennykerr** [microsoft/winrt-rs#169]
`RuntimeType` is purposefully limited to WinRT types while `ComInterface` is for any COM interface (even those that are not WinRT types). The trouble is that `RuntimeType` has `set_abi` while `ComInterface` does not (and `set_abi` is essential for most all COM interfaces) so it makes it very hard to use `ComInterface` to build meaningful generic functions (safely).

**Comment by rylev** [comment]
Talking with @kennykerr yesterday we agreed that the approach we should try out is to have a third trait, tentatively called `AbiTransferable`, that has two methods: `get_abi`  and `set_abi`. These would be for any types that can be used across the ABI boundary. We keep `ComInterface` and `RuntimeType` as they are to represent COM interfaces and any WinRT type that can used in WinRT generics respectively They both require the implementing type to be `AbiTransferable`.
