### ISSUE TITLE
Calling ABI methods not always unsafe

### ISSUE THREAD

**Issue by kennykerr** [microsoft/winrt-rs#176]
The following generated `unsafe` now sometimes causes an "unnecessary unsafe block" warning. Previously all of these calls to the ABI were unsafe but now thanks to recent safety improvements only those involving certain parameters are unsafe. 

https://github.com/microsoft/winrt-rs/blob/dfb144b85a253067e59cf4bc543b156606c2dc85/crates/winmd/src/types/method.rs#L250

**Comment by rylev** [comment]
I would argue that all ABI calls should be marked as unsafe. It is not safe to call outside of Rust because Rust cannot guarantee its safety properties are upheld when control flows to another language. I think the right solution is actually to mark all vtable fields as unsafe.

**Comment by kennykerr** [comment]
I mainly want to avoid the warnings, so that works for me. 👍
