### ISSUE TITLE
cargo nuget install panics when there is no metadata table in Cargo.toml

### ISSUE THREAD

**Issue by tim-weis** [microsoft/winrt-rs#179]
Steps to reproduce:

~~~cmd
cargo new nuget-test
cd nuget-test
cargo nuget install
~~~

Executing those commands results in the following error diagnostic:

> ``thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MalformedManifest', crates\cargo-nuget\src\main.rs:13:35``

This is ultimately caused by the return expression in `get_deps`
https://github.com/microsoft/winrt-rs/blob/dce2905e7932611b4a00cfdfa9556ae976226d61/crates/cargo-nuget/src/main.rs#L94
that subscribes inability to find any `metadata` tables to an error condition.

I would have expected that `nuget install` would turn into a no-op, in case there aren't any dependencies that require installation. Incidentally, this is what happens when there is an empty `[package.metadata.nuget_dependencies]` table in Cargo.toml.

Can the implementation be changed to always succeed when there's nothing to do? (Or, alternatively, emit a more accurate error diagnostic.)

**Comment by kennykerr** [comment]
Reopening as I still observe a crash.

```
C:\git\rust>cargo new repro
     Created binary (application) `repro` package

C:\git\rust>cd repro

C:\git\rust\repro>cargo winrt run
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MalformedManifest', crates\cargo-winrt\src\main.rs:18:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
