### ISSUE TITLE
"cargo nuget install" fails to copy binaries to target/debug folder

### ISSUE THREAD

**Issue by kennykerr** [microsoft/winrt-rs#180]
I'm testing the `Microsoft.AI.MachineLearning` API. Thanks to https://github.com/microsoft/winrt-rs/pull/177, this should work. 

Here's a simple repro. 

Cargo.toml is as follows:

```toml
[package]
name = "scratch"
version = "0.1.0"
edition = "2018"

[dependencies]
winrt = { path = "../winrt-rs" }

[package.metadata.nuget_dependencies]
"Microsoft.AI.MachineLearning" = "1.3.0"
```

src/main.rs is as follows:

```rust
winrt::import!(
    dependencies
        os
        nuget: Microsoft.AI.MachineLearning
    types
        microsoft::ai::machine_learning::*
);

fn main() -> winrt::Result<()> {
    use microsoft::ai::machine_learning::*;

    let tensor = TensorBoolean::create()?;
    assert!(tensor.tensor_kind()? == TensorKind::Boolean);
    println!("tensor {:?}", tensor);

    Ok(())
}
```

Now I run `cargo nuget install`. This downloads the nuget package and places the .winmd and .dlls in the `target\nuget\Microsoft.AI.MachineLearning` folder. **It does not** however copy the necessary .dlls into the `target\debug` folder.

`cargo build` succeeds but `cargo run` fails as it cannot find `Microsoft.AI.MachineLearning.dll` at run time.

```
C:\git\rust\scratch>cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target\debug\scratch.exe`
Error: Error { code: 0x80040154, message: "Class not registered" }
error: process didn't exit successfully: `target\debug\scratch.exe` (exit code: 1)
```

I can then copy the .dlls manually as follows:

```
C:\git\rust\scratch>copy target\nuget\Microsoft.AI.MachineLearning\win-x64\* target\debug\
target\nuget\Microsoft.AI.MachineLearning\win-x64\DirectML.dll
target\nuget\Microsoft.AI.MachineLearning\win-x64\Microsoft.AI.MachineLearning.dll
target\nuget\Microsoft.AI.MachineLearning\win-x64\onnxruntime.dll
        3 file(s) copied.
```

Now if I run it again, all is well:

```
C:\git\rust\scratch>cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target\debug\scratch.exe`
tensor TensorBoolean(Some(0x1ce42b28430))
```

The good news is the reg-free activation seems to be working nicely. 😉

**Comment by tim-weis** [comment]
I'm not sure whether *cargo-nuget* should copy the modules at all. This would entail (as far as I understand) that *cargo-nuget* enumerate all architectures available in the NuGet package, create appropriate output directories for each, and copy the modules to the right locations.

Driving the copying through a [build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html) seems to be a more natural option. The build script knows the target platform and (presumably) the per-architecture/per-configuration destination directories. A corollary of this knowledge is, that the build script can error out in case a NuGet package doesn't contain the required module(s) given the current target architecture/configuration.

**Comment by rylev** [comment]
This is an interesting point. cargo nuget obviously also knows about the target architecture its running on, but since "installation" happens at a different point in time than building, one could imagine that the architecture used for installing is different than the architecture used for building (e.g., for cross compiling). While it's a bit of a shame for `cargo nuget install` to have slightly different semantics than cargo install, for the normal use case where the build architecture and the target architecture are the same, this will work.
