### ISSUE TITLE
cargo-winrt doesn't handle dependencies in nested packages

### ISSUE THREAD

**Issue by kennykerr** [microsoft/winrt-rs#207]
Workaround is to move the the `[package.metadata.winrt.dependencies]` section to the root `Cargo.toml` file.

Here's a repro: https://github.com/kennykerr/scratch2

Repro steps:

```
C:\git\rust>git clone https://github.com/kennykerr/scratch2
Cloning...

C:\git\rust>cd scratch2

C:\git\rust\scratch2>cargo winrt build
   Compiling... 
error: proc macro panicked
 --> bindings\build.rs:1:1
  |
1 | / winrt::build!(
2 | |     dependencies
3 | |         nuget: Microsoft.Windows.SDK.Contracts
4 | |     types
... |
7 | |         windows::web::syndication::*
8 | | );
  | |__^
  |
  = help: message: Dependency C:\git\rust\scratch2\target\nuget\Microsoft.Windows.SDK.Contracts is not a file or directory

error: aborting due to previous error

error: could not compile `bindings`.

To learn more, run the command again with --verbose.
```

**Comment by rylev** [comment]
Panicking here is certainly wrong, but that's another issue. I'm wondering what the right behaivor should be. Should we look in the current crates dependencies for any local dependencies and run `cargo winrt` on those dependencies?

**Comment by kennykerr** [comment]
It seems that if we want symmetry between running "cargo run" and "cargo winrt run" then it should look for dependencies as that's what the former does.

**Comment by kennykerr** [comment]
And it's more than a usability issue with the cargo tool because I actually have to put the `[package.metadata.winrt.dependencies]` in the Cargo.toml of the outer crate rather than the bindings crate. That seems completely wrong.
