### ISSUE TITLE
From<HString> for String can panic

### ISSUE THREAD

**Issue by jstarks** [microsoft/winrt-rs#227]
`String` in Rust requires that the underlying buffer be a valid UTF-8 string. `HSTRING` in Windows does not require that the underlying buffer be a valid UTF-16 string--it can be any sequence of 16-bit integers, including unmatched surrogates. Therefore, it's not always possible to translate an `HSTRING` into a `String` (but it is, of course, always valid to go the other direction).

However, we have:

```rust
impl<'a> From<&'a HString> for String {
    fn from(hstring: &HString) -> Self {
        String::from_utf16(hstring.as_wide()).unwrap()
    }
}
```

This will panic if the `HSTRING` contains non-UTF-16 characters.

This can happen, for example, if a user has a file with a non-UTF-16 name and calls one of the WinRT directory enumeration APIs.

It seems that the fix for this would be to implement `From<HString>` for `OsString` instead, as `OsString` can encode any Windows wide string, not just valid Unicode strings. The user can then try to convert it to a `String` or `&str` dynamically, falling back to some reasonable behavior (or panicking!) as appropriate.

This will make using `HString` more annoying for callers, but there's no real alternative I can see.

**Comment by kennykerr** [comment]
We could use `String::from_utf16_lossy` instead.

**Comment by weltkante** [comment]
> We could use String::from_utf16_lossy instead.

dangerous when you expect strings to roundtrip through multiple API calls

**Comment by jstarks** [comment]
That will make it impossible to get the correct file names when enumerating a folder, for example.

**Comment by jstarks** [comment]
Certainly it would be reasonable to have a method `to_string_lossy` on `HString`, though (like `OsStr` has).

**Comment by kennykerr** [comment]
I'm in favor of `HString` behaving more like `OsStr` than `String`. It's designed for interop and developers should only use it on the boundary of an API.

**Comment by rylev** [comment]
Do we drop the From String conversions in favor of From for OsString? We can keep conversions to String through a TryFrom implementation.

**Comment by jstarks** [comment]
It's interesting that there appears to be no `TryFrom<OsString>` for `String`. Not sure if it's an oversight or if there's some principled reason. It might be good to understand why that is before adding `TryFrom<HString>`.

**Comment by rylev** [comment]
I would suspect it's because `TryFrom` is relatively new (since 1.34). OsString already has [`OsString::into_string`](https://doc.rust-lang.org/std/ffi/struct.OsString.html#method.into_string) which fills the same niche. I imagine it's simply that no one has added it, but it's possible I'm missing something.
