### ISSUE TITLE
Can't set `MediaPlaybackList.MaxPlayedItemsToKeepOpen`

### ISSUE THREAD

**Issue by ndarilek** [microsoft/winrt-rs#229]
Docs are [here](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybacklist.maxplayeditemstokeepopen?view=winrt-19041#Windows_Media_Playback_MediaPlaybackList_MaxPlayedItemsToKeepOpen). I'm otherwise using this class well, but can't seem to call:

```
playback_list.set_max_played_items_to_keep_open(1 as u32)?;
```

The cast probably isn't necessary--I just did it to be explicit. Is the issue here that it's a `Nullable<Uint32>`? I tried `Some(1)` with the same result.

Here is the error:

```
the trait bound `winrt::param::Param<'_, winrt_bindings::windows::foundation::IReference<u32>>: std::convert::From<std::option::Option<{integer}>>` is not satisfied
the following implementations were found:
  <winrt::param::Param<'a, T> as std::convert::From<&'a T>>
  <winrt::param::Param<'a, T> as std::convert::From<T>>
  <winrt::param::Param<'a, winrt::hstring::HString> as std::convert::From<&'a str>>
  <winrt::param::Param<'a, winrt::hstring::HString> as std::convert::From<std::string::String>>
required because of the requirements on the impl of `std::convert::Into<winrt::param::Param<'_, winrt_bindings::windows::foundation::IReference<u32>>>` for `std::option::Option<{integer}>`rustc(E0277)
```

Thanks.

**Comment by kennykerr** [comment]
Yes, WinRT's `IReference<T>` is conceptually the same as Rust's `Option<T>`. This is just waiting on #92 and then you should be able to simply write:

```rust
list.set_max_played_items_to_keep_open(1)?;
```

Until then, here's a workaround. You just need to create the boxed value yourself:

```rust
use winrt::TryInto;
use windows::media::playback::*;
use windows::foundation::*;

let object = PropertyValue::create_uint32(1)?;
let option: IReference<u32> = object.try_into()?;

list.set_max_played_items_to_keep_open(option)?;
```

**Comment by ndarilek** [comment]
Got it. Is there a workaround in the meantime?

**Comment by ndarilek** [comment]
OK, looks like I can create the `IReference` directly. Having some long 
rebuild times here even with a subcrate, but I'll report back if I have 
any issues I can't resolve. Thanks.

**Comment by kennykerr** [comment]
I included a workaround above. You shouldn't have long rebuild times if you're using a sub crate. Let us know if that becomes an issue.

**Comment by ndarilek** [comment]
Ah, crap, so you did. Sorry, I don't know how I missed that. :/
