### ISSUE TITLE
cargo winrt consistency

### ISSUE THREAD

**Issue by kennykerr** [microsoft/winrt-rs#247]
A few minor polish issues.

* Notice the indentation difference between `cargo install` and `cargo winrt install`.
* The latter injects a `:` which we should probably just remove now that we have colorization.
* Add a `Finished in 1m 03s` at the end both to tell you how long it took and as a quick visual that it completed and didn't silently fail.
* Add a `cargo winrt clean` option to remove nuget packages and ensure `cargo winrt install` fetches them again. Right now I have to run `cargo clean` just to make sure `cargo winrt install` actually updates the nuget packages but that blows away the cargo cache as well.

![image](https://user-images.githubusercontent.com/9845234/86400642-d7fec580-bc5d-11ea-9626-558c5b1da6d0.png)

**Comment by kennykerr** [comment]
@rylev pointed out there's a "force" option - we should document that.

https://github.com/microsoft/winrt-rs/blob/8a5d2a9a56327a3ac77ee3594931217da23a5951/crates/cargo-winrt/src/main.rs#L70

**Comment by zachlute** [comment]
With #258 merged, I believe everything mentioned in here is handled and this can be closed.

**Comment by kennykerr** [comment]
Thanks Zach!
