### ISSUE TITLE
IDesktopWindowXamlSourceFactory create_instance call fails in Rust/WinRT

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/winrt-rs#252]
Hi,

I'm trying out Rust/WinRT with the XAML Islands and I've been basically repeating the [C++ sample](https://github.com/microsoft/Xaml-Islands-Samples/tree/master/Standalone_Samples/CppWinRT_Basic_Win32App). This code keeps failing:

```rust
WindowsXamlManager::initialize_for_current_thread()
    .expect("Couldn't initialize WindowsXamlManager.");

let factory = winrt::factory::<DesktopWindowXamlSource, IDesktopWindowXamlSourceFactory>()
    .expect("Could not get IDesktopWindowXamlSourceFactory.");

let base_interface = Object::default();
let mut inner_interface = Object::default();

let desktop_source = factory.create_instance(base_interface, &mut inner_interface)
    .expect("Could not create an instance of DesktopWindowXamlSource.");
```

I'm using the same approach as @roblabla here: https://github.com/roblabla/ubuntu-installer/blob/master/src/main.rs#L29

The error happens when I try to `create_instance`:

```
Exception thrown at 0x00007FFEE6313E49 (KernelBase.dll) in xaml_islands.exe: WinRT originate error - 0x8000FFFF : 'Cannot activate WindowsXamlManager. Previous instance is still closing, please drain the Dispatcher before continue. See: https://go.microsoft.com/fwlink/?linkid=875495'.
thread 'main' panicked at 'Could not create an instance of DesktopWindowXamlSource.: Error { code: 0x8000FFFF, message: "Cannot activate WindowsXamlManager. Previous instance is still closing, please drain the Dispatcher before continue. See: https://go.microsoft.com/fwlink/?linkid=875495" }', src\main.rs:81:26
```

The sample in C++ does run fine, so I suspect it might be something wrong with how `create_instance` is generated by Rust/WinRT.

Here's the complete sample to reproduce: 
[xaml_islands.zip](https://github.com/microsoft/winrt-rs/files/4886377/xaml_islands.zip)

Thanks!

**Comment by roblabla** [comment]
What error are you getting? You have to put a correct manifest in order for XAML Islands to work. See:

- The RC File: https://github.com/roblabla/ubuntu-installer/blob/master/ubuntu-installer.rc
- The Manifest File: https://github.com/roblabla/ubuntu-installer/blob/master/ubuntu-installer.exe.manifest
- The build.rs to embed the manifest in the final exe: https://github.com/roblabla/ubuntu-installer/blob/master/build.rs

**Comment by roblabla** [comment]
The error we're getting:

```
thread 'main' panicked at 'Could not create an instance of DesktopWindowXamlSource.: Error { code: 0x8000FFFF, message: "Cannot activate WindowsXamlManager. Previous instance is still closing, please drain the Dispatcher before continue. See: https://go.microsoft.com/fwlink/?linkid=875495" }', src\main.rs:79:26
```

The line number points to `let desktop_source = factory.create_instance(base_interface, &mut inner_interface)`.

I didn't get that one while working on ubuntu-installer, so that's interesting. Running the snippet you provided right from the start of main() also causes the problem, so it's not a bad interaction with other parts of the system. An old build of ubuntu-installer (using a super old version of winrt-rs) still works on latest Win10, so there's a pretty high likelyhood that winrt-rs got a regression indeed.

**Comment by Alovchin91** [comment]
@roblabla Oh my, did I forget to post the error? 😅
I'm sorry, yes, this is the exact error I get! Running under debugger I can see it happening in the WinRT:

```
Exception thrown at 0x00007FFEE6313E49 (KernelBase.dll) in xaml_islands.exe: WinRT originate error - 0x8000FFFF : 'Cannot activate WindowsXamlManager. Previous instance is still closing, please drain the Dispatcher before continue. See: https://go.microsoft.com/fwlink/?linkid=875495'.
```

A similar code in C++ works, so it indeed seems like Rust/WinRT is not getting those `Object::default()` parameters correctly.

**Comment by kennykerr** [comment]
I just added a [composable test](https://github.com/microsoft/TestWinRT/pull/31) - we'll see if that's the issue and make sure that's working properly.

**Comment by kennykerr** [comment]
This PR adds support for creating composable types. Let me know if you're still running into issues here. 

https://github.com/microsoft/winrt-rs/pull/255

**Comment by Alovchin91** [comment]
Hi @kennykerr,

I've tried replacing Rust/WinRT dependency in Cargo.toml with `winrt = { git = "https://github.com/microsoft/winrt-rs", branch = "composable" }`,
and then I've replaced the code from the original post (starting with `let factory`) with
```rust
let desktop_source = DesktopWindowXamlSource::new()
    .expect("Could not create an instance of DesktopWindowXamlSource.");
```
but no luck, I still get the same error.

`cargo clean` doesn't solve the issue, rebooting the machine doesn't help either. I think this is something with how the parameters are passed into the `create_instance` ABI method.

Could it be because it's `*mut Option<...>` instead of `Option<...>` or `*mut <pointertype>`? Though `Option` should be transparent from my understanding, but maybe Rust does apply some marshaling there and it becomes a double-pointer?

**Comment by kennykerr** [comment]
I took a quick look at the Xaml source code where the "Cannot activate WindowsXamlManager. Previous instance is still closing..." message originates. This error is returned when Xaml determines that the app decided to begin shutting things down. Your Rust port of the C++ sample isn't quite right. Notice the C++ sequence looks something like this:

```C++
WindowsXamlManager manager = WindowsXamlManager::InitializeForCurrentThread();
DesktopWindowXamlSource source;
```

First the `WindowsXamlManager` is created (and kept alive) and only then is the `DesktopWindowXamlSource` created.

Your Rust port looks something like this:

```rust
WindowsXamlManager::initialize_for_current_thread()?;
let source = DesktopWindowXamlSource::new()?;
```

Since you let the `WindowsXamlManager` be destroyed before creating the `DesktopWindowXamlSource`, Xaml notices that it is shutting down and won't let you create the `DesktopWindowXamlSource`. 

I was able to get your Xaml Islands sample running by changing the following:

```rust
let manager = WindowsXamlManager::initialize_for_current_thread()
    .expect("Couldn't initialize WindowsXamlManager.");
```

**Comment by Alovchin91** [comment]
Whoops, indeed 😅 Thank you for checking this out!

It's apparently an interesting point in the Rust language because I've tried doing the following:

```rust
let _ = WindowsXamlManager::initialize_for_current_thread()
    .expect("Couldn't initialize WindowsXamlManager.");
```

And it also didn't work. Apparently the discard (`_`) as a variable name means pretty much the same as if there was no variable name at all.

Anyway it's a shame I couldn't figure it out myself 😞 Thanks again and sorry for the inconvenience!
