### ISSUE TITLE
Remove Microsoft.AI.MachineLearning dev/test dependency

### ISSUE THREAD

**Issue by kennykerr** [microsoft/winrt-rs#259]
Now that we have the nuget-based TestWinRT component, we no longer need to use the MachineLearning API for testing. Removing it should speed up developer inner loop as it's quite large.

**Comment by rylev** [comment]
Would it make sense to remove more tests (and replace with appropriate tests from the test component)? Perhaps some of what are currently tests really belong as examples.

**Comment by kennykerr** [comment]
Yes, I'd also like to get ride of the Xaml test. Loading the test component is much faster.

**Comment by kennykerr** [comment]
I discovered another regression - I'm going to remove MachineLearning but rather than remove Xaml I'm going to expand that test to import all namespaces. We'll just have to comment it out for local builds but at least the CI build can exhaustively test the entire OS type system until we're at a point where we have more coverage from the test component.
