### ISSUE TITLE
cargo winrt install is working pretty slow in low bandwidth environment

### ISSUE THREAD

**Issue by uhuntu** [microsoft/winrt-rs#260]
I tried "cargo winrt install" to install, but in my environment, it always stuck in
```
C:\Users\hunt\source\repos\winrt-rs>cargo winrt install
    Fetching KennyKerr.Windows.TestWinRT
    Fetching Microsoft.AI.MachineLearning
```

I tried adding verbose to see more information
```
C:\Users\hunt\source\repos\winrt-rs>cargo winrt install --verbose
   Resolving winrt_macros
  Installing 0 nuget dependencies
   Resolving winrt
  Installing 3 nuget dependencies
    Fetching KennyKerr.Windows.TestWinRT
  Requesting https://www.nuget.org/api/v2/package/KennyKerr.Windows.TestWinRT/1.0.16
  Requesting https://globalcdn.nuget.org/packages/kennykerr.windows.testwinrt.1.0.16.nupkg
   Retrieved data from https://globalcdn.nuget.org/packages/kennykerr.windows.testwinrt.1.0.16.nupkg
    Starting extraction of 'KennyKerr.Windows.TestWinRT'
   Searching zip file: _rels\.rels
   Searching zip file: KennyKerr.Windows.TestWinRT.nuspec
   Searching zip file: lib\uap10.0\TestComponent.winmd
       Found winmd file: "TestComponent.winmd"
   Searching zip file: runtimes\win10-x86\native\TestComponent.dll
       Found dll "TestComponent.dll" with arch "win10-x86" at path runtimes\win10-x86\native\TestComponent.dll
   Searching zip file: runtimes\win10-x64\native\TestComponent.dll
       Found dll "TestComponent.dll" with arch "win10-x64" at path runtimes\win10-x64\native\TestComponent.dll
   Searching zip file: [Content_Types].xml
   Searching zip file: package\services\metadata\core-properties\d677ecd8bcef4b7c825af36506771d04.psmdcp
   Searching zip file: .signature.p7s
    Fetching Microsoft.AI.MachineLearning
  Requesting https://www.nuget.org/api/v2/package/Microsoft.AI.MachineLearning/1.3.0
  Requesting https://globalcdn.nuget.org/packages/microsoft.ai.machinelearning.1.3.0.nupkg
```

I realized that machinelearning download always stuck at header request and almost never end.

I guess in good network environment, you might not ever observe it.

In the document here: https://docs.rs/curl/0.4.30/curl/easy/struct.Easy2.html#method.nobody
```
pub fn nobody(&mut self, enable: bool) -> Result<(), Error>
Indicate whether to download the request without getting the body
This is useful, for example, for doing a HEAD request.
By default this option is false and corresponds to CURLOPT_NOBODY.
```
Which means that when you do a curl easy transfer, by default it will require full body of content not just header, it is not make sense when you just want the header.

**Comment by kennykerr** [comment]
The [Microsoft.AI.MachineLearning](https://www.nuget.org/packages/Microsoft.AI.MachineLearning) nuget package is larger than most at around 164MB. It will take more time to download on a slow connection, but that's inevitable as the nuget package must actually be downloaded to retrieve the contents of the package.

Note that this particular package is only used for testing so simply using the [winrt-rs crate via crates.io](https://crates.io/crates/winrt) should not require you to use this nuget package. 

Also, I'm planning on removing some of these larger dev dependencies for efficiency. #259

**Comment by uhuntu** [comment]
> but that's inevitable as the nuget package must actually be downloaded to retrieve the contents of the package.

When you review the code, you can see actually there are several parts of curl transfer, some is requesting the header, some is requesting the body. What I mean is when you request the header, it actually request full body of content if you did not set nobody feature.

That results when you download content form the network, it will take twice times. Especially when you download large file like Microsoft.AI.MachineLearning in slow connection, it will be felt much long, because it took much time when it requests header. I can accept that it took time on really download, but I can not accept it took time on requesting just header.

The below code is requesting header, but actully it request full body if you do not set nobody.
```
let status = &mut None;
{
	let mut transfer = handle.transfer();
	transfer
		.header_function(|header| {
			let header = std::str::from_utf8(header).unwrap();
			if header.starts_with("HTTP/1.1 ") {
				let n = &header[9..12];
				*status = Some(n.parse::<u16>().expect("Should be number"));
			}
			true
		})
		.unwrap();
	print_verbose_status!("Requesting", &url);
	transfer.perform()?;
}
```

The below code is really download, I can accept it took time.
```
match status.expect("HTTP request did not have a status code") {
	200u16 => {
		print_verbose_status!("Retrieved", "data from {}", url);
		let mut bytes = Vec::new();
		{
			let mut transfer = handle.transfer();
			transfer
				.write_function(|d| {
					bytes.extend(d);
					Ok(d.len())
				})
				.map_err(|e| Error::DownloadError(e.into()))?;
			transfer.perform()?;
		}
		Ok(bytes)
	}
```

**Comment by kennykerr** [comment]
Thanks for the explanation. I haven't reviewed the download code, but if that's the case that's definitely something we should fix.

**Comment by uhuntu** [comment]
I have a PR here #257, but it was closed

**Comment by kennykerr** [comment]
The trouble is that PR included other unrelated improvements along with this fix, making it a lot harder to review and accept. If you'd be willing to create a new PR that simply fixes this issue it would be far more likely to be approved.

**Comment by uhuntu** [comment]
Thanks, a new PR here #262

**Comment by kennykerr** [comment]
Thanks for the contribution!
