### ISSUE TITLE
cannot use Win2D.uwp nuget package: error 0x80040154 "Class not registered" appears

### ISSUE THREAD

**Issue by milyin** [microsoft/winrt-rs#266]
Sample is in repository https://github.com/milyin/win2d_fail, sources also below
On 'cargo winrt run' command error 'Error: Error { code: 0x80040154, message: "Class not registered" }' is fired
Is it bug or am I'm doing something wrong?

src/main.rs
```
winrt::import!(
    dependencies
        os
        nuget: Win2D.uwp
    types
	microsoft::graphics::canvas::CanvasDevice
);

fn main() -> winrt::Result<()> {
    use microsoft::graphics::canvas::CanvasDevice;
    let _device = CanvasDevice::get_shared_device()?;
    Ok(())
}
```

cargo.toml
```
[package]
name = "win2d_fail"
version = "0.1.0"
edition = "2018"

[dependencies]
winrt = "0.7.1"

[package.metadata.winrt.dependencies]
"Win2D.uwp" = "1.25.0"
```

**Comment by kennykerr** [comment]
Win2D has a (hidden) dependency on a specific version of the CRT that only works (by default) in an app container. If you'd like to use Win2D from a regular Win32 desktop process then you need to add [Microsoft.VCRTForwarders.140](https://www.nuget.org/packages/Microsoft.VCRTForwarders.140/) as an additional dependency as follows:

```
[package.metadata.winrt.dependencies]
"Win2D.uwp" = "1.25.0"
"Microsoft.VCRTForwarders.140" = "1.0.6"
```

Rerun `cargo winrt install` and you should be good to go.

**Comment by milyin** [comment]
It works now. Thank you very much!
