### ISSUE TITLE
Change `build!` macro to be inline.

### ISSUE THREAD

**Issue by rylev** [microsoft/winrt-rs#268]
Currently in build scripts the `winrt::build!` macro generates a build function which the user then calls. This was because until the latest version of Rust, proc-macros were not allowed in expression position. With the latest release of Rust, the following would be possible in a build.rs:

```rust
fn main() {
    winrt::build!()
}
```

The only downside is we can only support the latest version of Rust. Given that we've not really made strong minimum supported Rust version (MSRV) claims, I think this is a fine tradeoff to make.

**Comment by kennykerr** [comment]
Let's do it.

**Comment by rylev** [comment]
Since we need to do a MSRV for const IID, I think we should wait until we do that.
