### ISSUE TITLE
Seeing AV locally but not in CI

### ISSUE THREAD

**Issue by rylev** [microsoft/winrt-rs#269]
When running tests locally, I get an AV on the xaml test. This seems to happen after all user code has run (including Drop code), so I'm not sure what's happening exactly. The following simple app reproduces the issue on my machine:

```rust
winrt::import!(
    dependencies
       os
    types
        windows::ui::xaml::Application
);
use windows::ui::xaml::Application;
use winrt::ComInterface;

fn main() {
    let app = Application::new().unwrap();
    assert_eq!(app.is_null(), false);
}
```

Interestingly, a potentially completely unrelated issue is that the ref counts I see when calling release on COM objects all are above zero leading me to believe, we're constantly leaking memory.

**Comment by kennykerr** [comment]
What version of Windows are you running?

**Comment by rylev** [comment]
v10.0.19041

**Comment by kennykerr** [comment]
It's more likely a difference in Xaml between 19041 and 18363, which I am running and likely the build server as well. That test doesn't use Xaml in the "prescribed" way so its not too surprising that it doesn't work. I can just remove it.

I also did a quick leak test and don't see any memory loss. Where are you seeing the ref count? COM implementations are allowed to lie (and often do) about outstanding references via AddRef/Release.

**Comment by tim-weis** [comment]
I just ran into a similar issue while implementing XAML hosting in a desktop application (which, incidentally, works!). Taking a step back I gave this repro a try, and can observe the same issue.

The Access Violation is triggered *after* control has returned from Rust and resumed in Microsoft's Universal CRT (`common_exit()`). I was able to capture a call-stack at the point of failure including symbol information:

	twinapi.appcore.dll!Microsoft::WRL::ActivationFactory<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<3>,Windows::ApplicationModel::Core::ICoreApplication,Windows::ApplicationModel::Core::ICoreApplication2,Windows::ApplicationModel::Core::ICoreApplication3,Windows::ApplicationModel::Core::ICoreApplicationExit,Windows::ApplicationModel::Core::ICoreImmersiveApplication,Windows::ApplicationModel::Core::ICoreImmersiveApplication2,Windows::ApplicationModel::Core::ICoreImmersiveApplication3,Windows::ApplicationModel::Core::ICoreApplicationUnhandledError,Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<3>,Microsoft::WRL::CloakedIid<Windows::ApplicationModel::Core::ICoreApplicationUseCount>,Microsoft::WRL::CloakedIid<IServiceProvider>,Microsoft::WRL::CloakedIid<IObjectWithSite>,Microsoft::WRL::CloakedIid<Windows::ApplicationModel::Infrastructure::ICoreApplicationInitializationPrivate>,Microsoft::WRL::CloakedIid<Windows::ApplicationModel::Core::ICoreApplicationPrivate>,Microsoft::WRL::CloakedIid<IUnhandledErrorForwarder>,Microsoft::WRL::CloakedIid<Windows::ApplicationModel::Core::IHostPrivate>,Microsoft::WRL::CloakedIid<Windows::ApplicationModel::Core::ICoreApplicationPrivate2>,Microsoft::WRL::CloakedIid<Windows::ApplicationModel::Core::ICoreApplicationPrivate3>,Microsoft::WRL::CloakedIid<Windows::ApplicationModel::Core::ICoreApplication_ApplicationWindow>,Microsoft::WRL::FtmBase>>,Microsoft::WRL::Details::Nil,Microsoft::WRL::Details::Nil,0>::Release()	Unknown
 	Windows.UI.Xaml.dll!ctl::ComPtr<ITextSelection2>::InternalRelease() Line 291	C++
 	[Inline Frame] Windows.UI.Xaml.dll!ctl::ComPtr<Windows::ApplicationModel::Core::ICoreApplication2>::{dtor}() Line 345	C++
 	Windows.UI.Xaml.dll!DirectUI::FrameworkApplication::HookBackgroundActivationEvents(bool fRegister) Line 1233	C++
 	Windows.UI.Xaml.dll!DirectUI::FrameworkApplication::~FrameworkApplication() Line 591	C++
 	Windows.UI.Xaml.dll!ctl::ComObject<DirectUI::FrameworkApplication>::`scalar deleting destructor'(unsigned int)	C++
 	Windows.UI.Xaml.dll!ctl::ComBase::ReleaseImpl() Line 307	C++
 	Windows.UI.Xaml.dll!ctl::ComObject<DirectUI::FrameworkApplication>::Release() Line 95	C++
 	Windows.UI.Xaml.dll!ctl::release_interface<DirectUI::SettingsFlyoutMetadata>(DirectUI::SettingsFlyoutMetadata * & pInterface) Line 137	C++
 	[Inline Frame] Windows.UI.Xaml.dll!DirectUI::FrameworkApplication::GlobalDeinit() Line 668	C++
 	Windows.UI.Xaml.dll!DeinitializeDll() Line 319	C++
 	Windows.UI.Xaml.dll!DllMain(HINSTANCE__ * hinstDLL, unsigned int fdwReason, void * __formal) Line 394	C++
 	Windows.UI.Xaml.dll!dllmain_dispatch(HINSTANCE__ * const instance, const unsigned long reason, void * const reserved) Line 200	C++
 	ntdll.dll!LdrpCallInitRoutine()	Unknown
 	ntdll.dll!LdrShutdownProcess()	Unknown
 	ntdll.dll!RtlExitUserProcess()	Unknown
 	kernel32.dll!ExitProcessImplementation()	Unknown
 	ucrtbase.dll!exit_or_terminate_process()	Unknown
 	ucrtbase.dll!common_exit()	Unknown
	xaml_application.exe!__scrt_common_main_seh() Line 295	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown

I didn't get much further in my analysis, but maybe this is of help to someone with more intimate knowledge about the Windows Runtime and XAML's intricacies.

**Comment by kennykerr** [comment]
Removed the offending test.
