### ISSUE TITLE
How to get functions and types from winrt namespace?

### ISSUE THREAD

**Issue by wusyong** [microsoft/winrt-rs#272]
Is there a way for us call functions from winrt namespace like when we do this in cpp? I couldn't find a way to do it in either import or build macro.

```cpp
using namespace winrt;

init_apartment(winrt::apartment_type::single_threaded);

single_threaded_vector<hstring>({winrt::to_hstring(s)})
```

**Comment by kennykerr** [comment]
The equivalent of the C++/WinRT `winrt namespace` is documented here:

https://docs.rs/winrt/

Note that we don't yet have Rust versions of `init_apartment` and `single_threaded_vector`.

**Comment by wusyong** [comment]
I see. That's a bit unfortunately but I think it's reasonable. I'll see if I can have some time to help it.
