### ISSUE TITLE
Format VTable structs for better readability

### ISSUE THREAD

**Issue by tim-weis** [microsoft/winrt-rs#282]
The generated VTable structs seem to have a fixed width, and wrap to a new line if that width is exceeded. That leads to fairly hard to read code, e.g.

~~~rust
#[repr(C)]
pub struct abi_IDataPackage where
{
    base__ : [usize ; 6], pub get_view : unsafe extern "system"
    fn(:: winrt :: NonNullRawComPtr < IDataPackage >, result__ : *
       mut < DataPackageView as :: winrt :: AbiTransferable > ::
       Abi,) -> :: winrt :: ErrorCode, pub properties : unsafe
    extern "system"
    fn(:: winrt :: NonNullRawComPtr < IDataPackage >, result__ : *
       mut < DataPackagePropertySet as :: winrt :: AbiTransferable
       > :: Abi,) -> :: winrt :: ErrorCode, pub
       // ...
~~~

Can this be changed to be more human-reader-friendly, something like this:

~~~rust
#[repr(C)]
pub struct abi_IDataPackage where
{
    base__ : [usize ; 6],
    pub get_view : unsafe extern "system" fn(
        ::winrt::NonNullRawComPtr<IDataPackage>,
        result__ : *mut <DataPackageView as ::winrt::AbiTransferable>::Abi,
    ) -> ::winrt::ErrorCode,
    pub properties : unsafe extern "system" fn(
        ::winrt::NonNullRawComPtr<IDataPackage>,
        result__ : *mut <DataPackagePropertySet as ::winrt::AbiTransferable>::Abi,
    ) -> ::winrt::ErrorCode,
   // ...
~~~

I understand that those are implementation details, and it's rare for a human to have to take a look at them at all. Human-readable code would still be nice to have (if it doesn't affect code generation/compile time), even if just for learning about the internals of this language projection.

**Comment by kennykerr** [comment]
It should be formatted with `rustfmt` - and for the most part that seems to work - perhaps there's an edge case or threshold where `rustfmt` gives up.

https://github.com/microsoft/winrt-rs/blob/36ba51037e694132dff4ed52d666a51a77cc083e/crates/macros/src/lib.rs#L131-L134

**Comment by tim-weis** [comment]
I wasn't aware, that the generated code gets piped through `rustfmt`. That sounds like a lot of wasted cycles, though, dropping all the semantic information from the code generator only to have it reconstructed in an external tool for formatting only.

I was going to profile the impact of `rustfmt` on code generation using [WinRT Perf Profile](https://github.com/rylev/winrt-profile), but that requires `dtrace` which is not available on my system. Maybe @rylev could gather some data on this.

In case dropping `rustfmt` in favor of formatting the code in the generator itself turns out to be a viable optimization opportunity, could this feature request be reconsidered?

**Comment by kennykerr** [comment]
Yes, we are actively working on build performance and considering a few options for replacing those parts that are under our control (code gen and formatting) and working with the Rust compiler team on the rest. Most of the time is currently spent inside the compiler, so there's much room for improvement across the board.

**Comment by kennykerr** [comment]
FYI. We're using [stress-rs](https://github.com/kennykerr/stress-rs) and [stress-cpp](https://github.com/kennykerr/stress-cpp) to compare Rust/WinRT with [C++/WinRT](https://github.com/microsoft/cppwinrt) - basically worst case bindings. Here are the relative numbers so far:

| | Intel | AMD |
| -- | -- | -- |
| C++ | 43 sec | 89 sec |
| Rust | 35 min | 55 min |
| | 48 x slower | 37 x slower |

Intel i7-8700K 6-Core
AMD Ryzen Threadripper 1950X 16-Core

Unfortunately, this is all largely single-threaded but clearly there's room for improvement. 😉

**Comment by kennykerr** [comment]
For reference, the following minimal repro produces a winrt.rs file with poor formatting. I'm not sure what triggers the formatting to go wonky though.

```rust
winrt::build!(
    dependencies
        os
    types
        windows::application_model::data_transfer::IDataPackage
);
```

**Comment by kennykerr** [comment]
I created an issue with rustfmt: https://github.com/rust-lang/rustfmt/issues/4365
