### ISSUE TITLE
Support for building pure UWP apps in Rust

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/winrt-rs#283]
This requires modifications to the Rust runtime so that it doesn't call prohibited APIs in a UWP app. Currently building a AppContainer app using Rust fails validation.

**Comment by bdbai** [comment]
Try using `*-uwp-windows-*` targets instead of `*-pc-windows-*` targets. Xargo is good at this cross compilation stuff.

Also see https://github.com/bdbai/first-uwp (not completed though)

**Comment by uhuntu** [comment]
Not sure if it is suitable to say here, but just FYI: https://github.com/uhuntu/win_ui

**Comment by Jaiganeshkumaran** [comment]
> Not sure if it is suitable to say here, but just FYI: https://github.com/uhuntu/win_ui

That's a desktop app, not a UWP app.

**Comment by kennykerr** [comment]
Yes, it's not that this isn't supported. It's just that we don't really have any good samples to share at the moment. Working on that! 😉

**Comment by kennykerr** [comment]
@robmikh also shared an example here: https://github.com/robmikh/minesweeper-rs/tree/uwp

Beyond that I'm focused on getting support in Rust for authoring WinRT types as that's a major obstacle in getting support for things like Xaml and UWP apps.
