### ISSUE TITLE
"cargo winrt --version" no longer displays version information

### ISSUE THREAD

**Issue by tim-weis** [microsoft/winrt-rs#296]
Previously, I had *cargo-winrt* version 0.7.0 installed. Running `cargo winrt --version` on the command line produced the following output:

>     cargo-winrt 0.7.0

After installing the latest version (0.7.2) of *cargo-winrt* by executing `cargo install cargo-winrt` produces the following output instead:

>     error: missing subcommand

(followed by the generic help text, that does include the `-v` and `--version` options). Was the option `--version` removed on purpose, or this is a regression?

**Comment by rylev** [comment]
This is something we got for free when using `clap`. We moved to a less compiler intensive CLI args parsing library and lost some of the niceties along the way. Thanks for reporting this!
