### ISSUE TITLE
To use ListView

### ISSUE THREAD

**Issue by uhuntu** [microsoft/winrt-rs#298]
I tried to use ListView here: https://github.com/uhuntu/win_ui/tree/lv

```
let lv = ListView::new()?;
lv.items()?.append("test")?;
```

But it failed on compile:

```
C:\Users\hunt\source\repos\win_ui>cargo build
   Compiling win_ui v0.1.0 (C:\Users\hunt\source\repos\win_ui)
   Compiling bindings v0.1.0 (C:\Users\hunt\source\repos\win_ui\bindings)
error[E0277]: the trait bound `winrt::param::Param<'_, winrt::object::Object>: std::convert::From<&str>` is not satisfied
  --> src\main.rs:48:17
   |
48 |     lv.items()?.append("test")?;
   |                 ^^^^^^ the trait `std::convert::From<&str>` is not implemented for `winrt::param::Param<'_, winrt::object::Object>`
   |
   = help: the following implementations were found:
             <winrt::param::Param<'a, T> as std::convert::From<&'a T>>
             <winrt::param::Param<'a, T> as std::convert::From<T>>
             <winrt::param::Param<'a, winrt::hstring::HString> as std::convert::From<&'a str>>
             <winrt::param::Param<'a, winrt::hstring::HString> as std::convert::From<std::string::String>>
   = note: required because of the requirements on the impl of `std::convert::Into<winrt::param::Param<'_, winrt::object::Object>>` for `&str`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `win_ui`.

To learn more, run the command again with --verbose.
```

**Comment by bdbai** [comment]
Conversion from a string to an object involves boxing, which is under development (see #297). Before #297 is landed, boxing can be achieved by [PropertyValue.CreateString](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.propertyvalue.createstring). Also see https://github.com/microsoft/winrt-rs/blob/master/tests/boxing.rs on its usage.

**Comment by uhuntu** [comment]
> Conversion from a string to an object involves boxing, which is under development (see #297). Before #297 is landed, boxing can be achieved by [PropertyValue.CreateString](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.propertyvalue.createstring). Also see https://github.com/microsoft/winrt-rs/blob/master/tests/boxing.rs on its usage.

Thanks for the hint, it works.
https://github.com/uhuntu/win_ui/commit/6de9d9e1b7d8361334ec4ce84efadcb61654205b

**Comment by kennykerr** [comment]
Basic boxing support is now included.
