### ISSUE TITLE
To use IVector

### ISSUE THREAD

**Issue by uhuntu** [microsoft/winrt-rs#305]
I see here a comment https://github.com/Microsoft/cppwinrt/issues/13#issuecomment-298284852

I would like to do the same thing in rust

```
let items: IVector<IInspectable> = ???;

let item = PropertyValue::create_string("hello").unwrap();
items.append(item).unwrap();

list_view.set_items_source(items).unwrap();
```

But what should I do ?

**Comment by kennykerr** [comment]
Creating an `IVector<T>` implementation depends on #81. For now, the best you can do is use an existing implementation. You can for example use [C++/WinRT](https://github.com/microsoft/cppwinrt) to create a component (DLL) that returns an empty `IVector<T>` that you can then populate in Rust.

**Comment by uhuntu** [comment]
Yeah, I realized that, but still thanks for your hint.

**Comment by kennykerr** [comment]
While there isn't a stock implementations of `IVector` just yet, you should now be able to use the `implement` macro to implement this interface yourself.
