### ISSUE TITLE
[Feature Request] Full documentation builds on Docs.rs

### ISSUE THREAD

**Issue by Kixiron** [microsoft/winrt-rs#309]
The documentation for winrt on docs.rs are currently very sparse, being able to see the whole spectrum of available APIs would be fantastic!
I think the best strategy for this would be to use the natively available winmd files contained in the [docs.rs windows docker container](https://github.com/rust-lang/crates-build-env/blob/master/windows/Dockerfile). I'll admit that I'm not a windows expert, so if some setup is still required then [vcpkg](https://github.com/rust-lang/crates-build-env/blob/master/windows/vc-packages.txt) and [choco](https://github.com/rust-lang/crates-build-env/blob/master/windows/choco-packages.txt) packages can be added to the build environment (adding further windows build tools may be involved, but it's still not that hard to do). From there it's fairly easy, docs.rs allows [detecting when you're building in it](https://docs.rs/about/builds) using both the `DOCS_RS` environmental variable for build scripts and by [setting features](https://docs.rs/about/metadata) so that things can be annotated with `#[cfg(docsrs)]`
If y'all are interested, I'd love to help whoever or make a PR myself

**Comment by kennykerr** [comment]
Hey, that's an interesting idea. However, the winmd files don't contain any documentation. They only contain enough information to describe the shape of the API surface. You can for example [load up all of the APIs](https://github.com/kennykerr/stress-rs/blob/master/bindings/build.rs) into a Rust crate and then run `cargo doc` on that. But to actually get documentation you'd need to find out where that's stored and somehow splice that in.

**Comment by Kixiron** [comment]
I think that's alright, only having API information is pretty run-of-the-mill for sys-like crates (which I think winrt reasonably fits into). Simply being able to see the apis available without having to do any extra user-sided work can be a really good thing, both for the lazy ~~like me~~ and people who just want to see if something's possible or have a question

**Comment by reflectronic** [comment]
I do not think posting the documentation for the Windows SDK on docs.rs will buy you much. The only thing you would gain is being able to see the signatures in Rust. None of the examples in the docs pages would be translated, you would not be able to filter the APIs by SDK version, and all of the concept topics would have to link back to the Microsoft docs website.

As many new Windows APIs will be moving out of the main Windows SDK, and into separate libraries acquired from NuGet, Rust/WinRT could create documentation comments when projecting components from NuGet: 
- If you look at the [Microsoft.Windows.SDK.Contracts](https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts) package, and unzip the nupkg file, you'll find the documentation for the Windows SDK in [XML documentation comment](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/) format under `ref/netstandard2.0/en`.
- For packages like [WinUI](https://www.nuget.org/packages/Microsoft.WinUI) and [Win2D](https://www.nuget.org/packages/Win2D.uwp), you can find the XML documentation comments under `lib/uap10.0`. 

Those are already locations where `cargo winrt` looks for WinMD files, and it could certainly look for XML files as well to generate doc comments from. The schema is documented in the [C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments#processing-the-documentation-file). (I don't know where documentation for the `os` metadata would be obtained, but that is probably just another reason to [remove it altogether.](https://github.com/microsoft/winrt-rs/issues/304))

**Comment by Kixiron** [comment]
I guess the thing I don't understand is "why not?". There's no detriment to posting on docsrs, we provide our service for free and setup/maintenance would be super minimal, I'd love to make a PR for it

**Comment by rylev** [comment]
I think there's a misunderstanding of what this crate does. This crate simply provides tooling for generating WinRT backed types based on metadata along with fundamental helper types that are needed for any WinRT library. All that code (with the exception of Windows.Foundation - which we should look into providing docs for if we can) will be documented and available on docs.rs. A user is free to use this library and generate bindings to the Windows SDK, but this crate will not do that. That theoretical crate can then provide documentation for the code it is generating. That's not the job of this crate.

**Comment by ChrisDenton** [comment]
@rylev Could I ask for clarification? What I think is being asked here is for docs.rs to host winrt's auto-generated documentation (with all features enabled). It's easy enough to do this locally but it would be more convenient for this to be hosted on docs.rs, no?

All that's needed for this is to add the required cargo metadata (and a `#[cfg]`).

**Comment by Kixiron** [comment]
Enabling documentation builds doesn't require documenting everything, it's very common for that *not* to be the case with this type of crate

- [`llvm-sys`](https://docs.rs/llvm-sys/100.1.0/llvm_sys/)
- [`libusb1-sys`](https://docs.rs/libusb1-sys/0.3.7/libusb1_sys/)
- [`ipp-sys`](https://docs.rs/ipp-sys/0.4.5/ipp_sys/)
- [`libudev-sys`](https://docs.rs/libudev-sys/0.1.4/libudev_sys/)
- [`jq-sys`](https://docs.rs/jq-sys/0.2.2/jq_sys/)
...And many many others

**Comment by rylev** [comment]
@ChrisDenton can you explain which APIs you’re not seeing? Again, the Windows SDK is not part of this crate. This crate can be used to generate code for the Windows SDK but that code would not live in this crate. Perhaps I’m missing something?

**Comment by SteveLauC** [comment]
I want the doc to live in doc.rs because the current link could crash Chrome:

<img width="992" height="468" alt="Image" src="https://github.com/user-attachments/assets/c513a235-0c44-4ae3-97af-1eab5b8d82f4" />

**Comment by riverar** [comment]
@SteveLauC Can't/won't happen, docs.rs isn't designed for such a large crate.

There's not much in those docs anyway; they're pretty useless. You're better off just looking at the Win32 docs and extrapolating from that. And hitting our feature search page for Cargo.toml programming.

**Comment by SteveLauC** [comment]
I think it should be a bug:

<img width="526" height="74" alt="Image" src="https://github.com/user-attachments/assets/d041e631-0028-4bfa-a6a6-6280849c5e5c" />

Searching causes Chrome to use 400% CPU, eventually leading to a crash.

I can easily reproduce this, in case you want my environments:

```sh
$ sw_vers
ProductName:            macOS
ProductVersion:         26.0
BuildVersion:           25A5306g

$ uname -a
Darwin Steves-MacBook-Air.local 25.0.0 Darwin Kernel Version 25.0.0: Mon Jun 30 22:07:46 PDT 2025; root:xnu-12377.0.132.0.2~69/RELEASE_ARM64_T8103 arm64
```

Chrome: Version 138.0.7204.101 (Official Build) (arm64)

**Comment by tim-weis** [comment]
I don't think this would change anything. It's not the hosting platform that causes browsers to struggle. It's the size of the documentation. And there aren't any more options left to trim that down any further.

**Comment by SteveLauC** [comment]
Get it, thanks for letting me know that
