### ISSUE TITLE
Proper way to check if an async .get() return value is null

### ISSUE THREAD

**Issue by chenxiaolong** [microsoft/winrt-rs#314]
Apologies if this issue tracker isn't the right place for questions.

What is the proper way to check if an object is null? For example,
```
let device = BluetoothLEDevice::from_bluetooth_address_async(addr)?.get()?;
println!("{:?}", device);
```
may return something like `BluetoothLEDevice(Some(0x1fe12692f50))` or `BluetoothLEDevice(None)`. I've been using:
```
if device.get_abi().is_none() {
    // ...
}
```
to indirectly determine if `device.ptr` is null. Is this current the best way to do it (in version 0.7.2)?

**Comment by kennykerr** [comment]
I would avoid relying on the ABI. You should be able to use the `ComInterface` trait as follows:

```rust
use winrt::ComInterface;

let device = BluetoothLEDevice::from_bluetooth_address_async(123)?.get()?;

if device.is_null() {

} else {

}
```

**Comment by chenxiaolong** [comment]
Thank you! Not sure how I missed that.
