### ISSUE TITLE
How to use InputInjector

### ISSUE THREAD

**Issue by jcdickinson** [microsoft/winrt-rs#316]
I'm trying to use `InputInjector` and this is as much as I have managed:

```rust
use winrt::import;

import!(
    dependencies
        os
    types
        windows::ui::input::preview::injection::InputInjector
        windows::system::VirtualKey
);

use std::time::Duration;
use windows::ui::input::preview::injection::{InjectedInputKeyboardInfo, InputInjector};
use winrt::Array;

fn main() -> winrt::Result<()> {
    let injector = InputInjector::try_create()?;

    loop {
        let info = InjectedInputKeyboardInfo::new()?;
        info.set_virtual_key(9)?;
        let mut arr = Array::with_len(1);
        arr[0] = info;
        injector.inject_keyboard_input(winrt::Param::Owned(arr))?;
        std::thread::sleep(Duration::from_secs(5));
    }
}
```

It fails to compile with this error (on the `inject_keyboard_input` line):

```
the trait `winrt::AbiTransferable` is not implemented for `winrt::Array<windows::ui::input::preview::injection::InjectedInputKeyboardInfo>`
```

I have also tried `Param::Borrowed`. Any suggestions?

**Comment by jcdickinson** [comment]
Related: I can't figure out how to extract the constant value from `VirtualKey` - if that is at all possible.

**Comment by kennykerr** [comment]
The `inject_keyboard_input` method is expecting a collection interface (`IIterable<T>`) rather than an array. That explains the parameter mismatch. Unfortunately, Rust/WinRT doesn't yet support implementing polymorphic collections. I'm working on that now. https://github.com/microsoft/winrt-rs/issues/81
