### ISSUE TITLE
Referencing winrt dependency with git remote link doesn't install required nugets for the cached repo

### ISSUE THREAD

**Issue by ryanlai2** [microsoft/winrt-rs#318]
I reference the winrt dependency like this in my toml:
```
[dependencies]
winrt = { git = "https://github.com/microsoft/winrt-rs.git", branch="master" }

[build-dependencies]
winrt = { git = "https://github.com/microsoft/winrt-rs.git", branch="master" }
```
When I go ahead and do ``` cargo winrt install ```, ``` cargo winrt build ```, the build complains about missing winrt dependencies when trying to compile winrt v0.7.2.
![image](https://user-images.githubusercontent.com/16694211/90927173-64e61580-e3a9-11ea-9193-6b5c8a47bf28.png)

I went to the cached winrt-rs repo and did a ``` cargo winrt install ``` before building my main project and my build worked.
![image](https://user-images.githubusercontent.com/16694211/90927239-92cb5a00-e3a9-11ea-8b75-f8a1e53a1ebd.png)

**Comment by rylev** [comment]
Closing this as this was an issue with code that is not released on crates.io and no longer on the main branch.
