### ISSUE TITLE
The crate no longer builds when used as a dependency due to missing WinRT dependencies

### ISSUE THREAD

**Issue by rylev** [microsoft/winrt-rs#321]
Because of https://github.com/microsoft/winrt-rs/pull/297, WinRT-rs no longer builds when used as a dependency, because of missing WinRT dependencies. In order for the crate to build, the WinRT dependencies must be present. This requires the end user to specify the WinRT dependencies of WinRT-rs in its Cargo.toml file. This is obviously not ideal. 

There's no obvious way to fix this. We could have WinRT-rs install its dependencies inside of its build script. Rust's "best practices" discourage fetching resources from the internet during a build.rs script so we'll probably want to avoid that. We could, however, include the WinRT dependencies as submodules in WinRT code base and reference them as local dependencies. This would allow installation without accessing the internet.

**Comment by kennykerr** [comment]
Once we have #320 we can simply copy the winmd files from the SDK nuget package into a subfolder in this repo. The build can then directly access them there instead of having to download them.
