### ISSUE TITLE
Help implementing this event handler

### ISSUE THREAD

**Issue by ndarilek** [microsoft/winrt-rs#330]
Hey folks, sorry once more if there is a better support channel for this. I'm trying to implement a callback for [this event](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybacklist.currentitemchanged?view=winrt-19041) (is this a delegate?) and don't know how to go about it. I went as far as cracking open the generated code, but it's a bit obtuse:

```
                pub fn current_item_changed<
                    'a,
                    T0__: ::std::convert::Into<
                        ::winrt::Param<
                            'a,
                            super::super::foundation::TypedEventHandler<
                                MediaPlaybackList,
                                CurrentMediaPlaybackItemChangedEventArgs,
                            >,
                        >,
                    >,
                >(
```

I mean, I get in general what that does, but there are bunches of generics and conversions there, and I'm still not super familiar with the WinRT APIs. Things I've tried:

```
        self.playback_list.current_item_changed(|args| {
            println!("Got it!");
        });
...
        self.playback_list.current_item_changed(|this, args| {
            println!("Got it!");
        });
```

Help welcome. Thanks!

**Comment by kennykerr** [comment]
Hi Nolan,

Rust/WinRT doesn't yet automatically bind a lambda/closure to a delegate parameter. I intend to support this, but as of now you need to create the delegate yourself. It should look something like this:

```rust
list.current_item_changed(TypedEventHandler::new(|_sender, _args| {
    // do stuff here
    Ok(())
}))?;
```

**Comment by ndarilek** [comment]
Thanks, almost got it. I hope I can ask one more quick question. In my 
callback I have:


```

letold_item=args.old_item()?;
letnew_item=args.new_item()?;
println!("Here: {:?}, {:?}", old_item, new_item);
```
And this shows things like:
Here: MediaPlaybackItem(Some(0x1d20fdbdc90)), 
MediaPlaybackItem(Some(0x1d20fdbe410)) Here: 
MediaPlaybackItem(Some(0x1d20fdbe410)), MediaPlaybackItem(None)
I.e. the last two media tracks appear sane. But how do I get at the 
`Option` bundled there? I've tried `*old_item`, `old_item.0` and a few 
other things, but nothing seems to let me get at their contents. Trying 
to determine when one or the other is assigned or `None` so I can take 
appropriate action.
Thanks a bunch.

**Comment by kennykerr** [comment]
The `println` macro is not doing a great job of printing out the object since it only really knows that it holds a pointer to the underlying implementation. That happens to be modeled as an `Option` but that's not particularly important for your purposes.

According to the docs, both `old_item` and `new_item` return a [MediaPlaybackItem](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybackitem?view=winrt-19041) object. As you can see, it has various properties that you can inspect.

**Comment by ndarilek** [comment]
That's what I thought initially too, but when I do:


`old_item.source()`;`
I get this. Is it a known bug or should I file a new one?
```
thread ' <unnamed>' panicked at 'The `this` pointer was null when 
calling method', C:\Users\Nolan 
Darilek\projects\tts-rs\target\debug\build\tts_winrt_bindings-29a4e8928352f4d1\out/winrt.rs:90305: 
26 stack backtrace: 0: backtrace::backtrace::trace_unsynchronized at 
C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66 
1: std::sys_common::backtrace::_print_fmt at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:78 
2: std::sys_common::backtrace::_print::{{impl}}::fmt at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs 
:59 3: core::fmt::write at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\fmt\mod.rs 
:1076 4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr> at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\io\mod.rs:1537 
5: std::sys_common::backtrace::_print at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:62 
6: std::sys_common::backtrace::print at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs 
:49 7: std::panicking::default_hook::{{closure}} at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs: 
198 8: std::panicking::default_hook at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs: 
217 9: std::panicking::rust_panic_with_hook at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs: 
526 10: std::panicking::begin_panic_handler at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs 
:437 11: core::panicking::panic_fmt at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\panicking.rs 
:85 12: core::option::expect_failed at 
/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\option.rs: 
1261 13: 
core::option::Option<winrt::com::raw_ptr::NonNullRawComPtr<tts_winrt_bindings::windows::media::playback::IMediaPla 
ybackItem>>::expect<winrt::com::raw_ptr::NonNullRawComPtr<tts_winrt_bindings::windows::media::playback::IMediaPlaybackI 
tem>> at C:\Users\Nolan 
Darilek\scoop\persist\rustup\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\l 
ibcore\option.rs :344 14: 
tts_winrt_bindings::windows::media::playback::MediaPlaybackItem::source 
at . 
\target\debug\build\tts_winrt_bindings-29a4e8928352f4d1\out\winrt.rs 
:90304 15: tts::backends::winrt::{{impl}}::init_callbacks::{{closure}} 
at .\src\backends\winrt.rs :75 16: 
tts_winrt_bindings::windows::foundation::impl_TypedEventHandler<tts_winrt_bindings::windows::media::playback::Medi 
aPlaybackList, 
tts_winrt_bindings::windows::media::playback::CurrentMediaPlaybackItemChangedEventArgs, 
closure-0>::invoke<tts_winrt_bindings: at .\ 
target\debug\build\tts_winrt_bindings-29a4e8928352f4d1\out\winrt.rs: 
12200 17: DllCanUnloadNow 18: DllCanUnloadNow 19: DllCanUnloadNow 20: 
DllCanUnloadNow 21: RtwqShutdown 22: RtwqShutdown 23: 
RtwqAllocateSerialWorkQueue 24: RtlInitializeCriticalSection 25: 
LdrAccessResource 26: BaseThreadInitThunk 27: RtlUserThreadStart ```

**Comment by kennykerr** [comment]
Presumably there may not be an "old item" so you may have to check before you try to use it. Perhaps something like this:

```rust
let old = args.old_item()?;

if !old.is_null() {
    let source = old.source()?;
}
```

The `is_null` method is available on the `ComInterface` trait so you may need to add:

```rust
use winrt::ComInterface;
```

I'm still considering a simpler syntax but hopefully that gets you unblocked for now.

**Comment by ndarilek** [comment]
Got it, thanks for pointing me to `is_null`. I assumed everything would 
be an `Option` if nullable. I'll check that going forward.


Thanks for all your patient help.
