### ISSUE TITLE
Casting support?

### ISSUE THREAD

**Issue by ndarilek** [microsoft/winrt-rs#352]
Apologies if I've missed this. Is there support for casting in cases where methods return interfaces, but you know there is definitely a specific implementor in the property?

I'm trying to get a [MediaPlaybackList](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Playback.MediaPlaybackList?view=winrt-19041), which implements [IMediaPlaybackSource](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.imediaplaybacksource?view=winrt-19041) from a [MediaPlayer](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Playback.MediaPlayer?view=winrt-19041). I've tried:

```
let source: MediaPlaybackList = sender.source()?;
let source: MediaPlaybackList = sender.source()?.into();
```

Is this at all possible, even unsafely?

Thanks.

**Comment by kennykerr** [comment]
You can use the `winrt::ComInterface` trait's `try_query` method. I am planning on [cleaning this up](https://github.com/microsoft/winrt-rs/issues/302) so that it's a little less confusing.

**Comment by ndarilek** [comment]
Hmm, looking at the try_query tests and am a bit confused. Currently doing:


```rust

player.media_ended(TypedEventHandler::new(|sender: &MediaPlayer, _args| {
println!("ended");
letsource=sender.source()?;
letsource: MediaPlaybackList=source.try_query()?;
```
Getting:
```
66 | let source: MediaPlaybackList = source.try_query()?; | ^^^^^^^^^ 
method not found in 
`tts_winrt_bindings::windows::media::playback::IMediaPlaybackSource` ```
I have:
```
usewinrt::ComInterface;
```
in my code. What am I missing?
Thanks.

**Comment by ndarilek** [comment]
Sorry, don't want to add noise, but I still need help with this. Is there additional boilerplate needed in build.rs to use `try_query`? I thought that was defined in `ComInterface`, which I've definitely imported to get `is_null`. I've looked at the test cases, and nothing jumps out at me. Should I be able to cast from a returned interface to a specific class? The tests cast to `IStringable` which is not what I want (I.e. I'm going *from* an interface, not *to* one.)

Thanks.

**Comment by kennykerr** [comment]
Hi Nolan, I'm not familiar with this particular API, but if you can share a complete and minimal repro that I can quickly compile I should be able to take a look and see if I can spot what's tripping you up.

**Comment by ndarilek** [comment]
OK, just realized that try_query isn't in 0.7.2, which is why it wasn't 
working for me. Or, at least, assuming the "v0.7" tag is 0.7.2, it isn't 
there.


So I suppose that begs 2 questions. 1. Is casting supported in 0.7.2? 2. 
If not, will there be a release that supports it soon? I have a library 
on crates.io, so depending on Git isn't an option.


Thanks.

**Comment by kennykerr** [comment]
Here's a casting example that works with `0.7.2`:

```rust
use winrt::*;

import!(
    dependencies
        os
    types
        windows::foundation::Uri
);

fn main() -> Result<()> {
    use windows::foundation::*;

    let uri = Uri::create_uri("http://kennykerr.ca")?;

    let s: IStringable = uri.try_into()?;
    println!("{}", s.to_string()?);

    let u: Uri = s.try_into()?;
    println!("{}", u.domain()?);

    Ok(())
}
```

**Comment by ndarilek** [comment]
OK, figured it out. The call to `try_into` suggested the standard Rust 
`TryInto` type be imported, which doesn't seem compatible in this context.


`use winrt::*;` got me what I needed and the cast worked. Guessing 
there's some local trait that provides this, but for some reason my 
loadOutDirsFromCheck setting still doesn't work so it wasn't suggested.


Thanks again for all the help.

**Comment by kennykerr** [comment]
No worries, thanks for being an early adopter! A lot work is going into the next version to remove a lot of the oddities and make it more idiomatic in Rust.
