### ISSUE TITLE
Failure to build a project using winrt-rs in a workspace

### ISSUE THREAD

**Issue by Enigmatrix** [microsoft/winrt-rs#368]
Example repo: https://github.com/Enigmatrix/winrt_workspace_test

Building the above repo gives an error when importing any type. e.g. in the case above,
![image](https://user-images.githubusercontent.com/12296254/100507302-4cf01000-31a8-11eb-8131-cdf941d6151b.png)
Using commit https://github.com/microsoft/winrt-rs/commit/38b7bea9a17930e55145a2b577b956e8193521ad

**Comment by kennykerr** [comment]
Thanks for the repro! I'm working on #351 that should also fix this issue. I'll check your repro to make sure. As a workaround, you can place the `[package.metadata.winrt.dependencies]` section in the outer toml file.

**Comment by Enigmatrix** [comment]
Wow, thanks!
