### ISSUE TITLE
how to return custom error messages through winrt::Result?

### ISSUE THREAD

**Issue by milyin** [microsoft/winrt-rs#369]
I want to return my own error message in winrt::Result. To do that I'm doing this:

```
winrt::import!(
    dependencies
        os
    types
);

fn main() {
  let e = winrt::Error::new(winrt::ErrorCode(0), "My error message");
  println!("{}", e.message());
}
```

This code unexpectedly prints "The operation completed successfully." - default message for error with code 0.

Debugging this I found that in 'Error::message(&self)' method the condition "if !self.info.is_null()" fails and message() method fallbacks to creating default error message for specified error code.

Probably the "info: IResrictedErrorInfo" is null because flag UseSetErrorInfo is not set by RoSetErrorReportingFlags, as specified here: https://docs.microsoft.com/en-us/windows/win32/api/roerrorapi/nf-roerrorapi-rooriginateerror:

>  If the UseSetErrorInfo flag is set by calling the RoSetErrorReportingFlags function, and the calling thread has been initialized in COM, the function creates an appropriate error object that supports IRestrictedErrorInfo and associates it with the COM channel by calling SetErrorInfo. 

Unfortunately it's still hard for me to directly call windows API from Rust, so I can't test this hypothesis right now

**Comment by kennykerr** [comment]
That's because zero is the value for a success code rather than a failure code. Try this instead:

```rust
const E_FAIL: winrt::ErrorCode = winrt::ErrorCode(0x80004005);
let e = winrt::Error::new(E_FAIL, "My error message");
println!("{}", e.message());
```

You can use the `is_ok` and `is_err` methods to determine whether an `ErrorCode` represents success or failure. This is based on the structure of an [HRESULT](https://en.wikipedia.org/wiki/HRESULT).

**Comment by milyin** [comment]
Thank you! WIth this error code this works. Though I tried to use other error codes (1,2,30 for example) and the default messages for these errors were printed.
So it's still unclear for me how could I know that the 0x80004005 value should be used?

**Comment by kennykerr** [comment]
Because those are all success codes. If you follow the link I shared and look at the structure of an HRESULT, you will see that bit 31 is the severity bit. If, and only if, that bit is set (0x8000_0000) will the error code represent failure rather than success.

**Comment by kennykerr** [comment]
By the way, nice game! 👍

**Comment by milyin** [comment]
Thank you! Will try to keep it up to developmennt of this great winrt project

**Comment by kennykerr** [comment]
Thanks, here's an example of how you might use Win2D with the latest version of winrt-rs.

https://github.com/kennykerr/win2d-rs
