### ISSUE TITLE
Blocking Waiters should use WaitOnAddress

### ISSUE THREAD

**Issue by smj389** [microsoft/winrt-rs#371]
I noticed that in a few place `CreateEventW` and `WaitForSingleObject` is used for a simple waiter. e.g.

https://github.com/microsoft/winrt-rs/blob/d50b2d690700270c6f4138ee0b085c9b8a686306/crates/gen/src/types/futures.rs#L73
https://github.com/microsoft/winrt-rs/blob/83669a4f1ad7b41cffb11d2243d824b2fbdba718/src/runtime/waiter.rs

Given that this is targeting Windows 8+ would not `WaitOnAddress` be more performant? You avoid the overhead of `CreateEventW` and `CloseHandle`.

Something on the lines of
```Rust
pub(crate) struct Waker {
    state: AtomicU32,
}
impl Waker {
    pub(crate) fn new() -> StackWaker {
        StackWaker {
            state: AtomicU32::new(0),
        }
    }

  pub(crate) fn wake(&self) {
        if self.state.compare_and_swap(0, 1, Ordering::AcqRel) == 0 {
            unsafe {
                WakeByAddressAll(self.state.as_mut_ptr() as PVOID);
            }
        }
    }

    pub(crate) fn wait(&self) {
        unsafe {
            while self.state.load(Ordering::Acquire) != 1 {
                let mut wait: u32 = 0;
                WaitOnAddress(
                    self.state.as_mut_ptr() as PVOID,
                    &mut wait as *mut u32 as PVOID,
                    std::mem::size_of::<u32>(),
                    INFINITE,
                );
            }
        }
    }
    pub(crate) fn wait_with_timeout(&self, duration: std::time::Duration) -> bool {
        let d = u32::try_from(duration.as_millis()).unwrap_or(INFINITE);
        unsafe {
            while self.state.load(Ordering::Acquire) != 1 {
                let mut wait: u32 = 0;
                let result = WaitOnAddress(
                    self.state.as_mut_ptr() as PVOID,
                    &mut wait as *mut u32 as PVOID,
                    std::mem::size_of::<u32>(),
                    d,
                );
                if result == FALSE && GetLastError() == ERROR_TIMEOUT {
                    return false;
                }
            }
            true
        }
    }

}
```
In the case of https://github.com/microsoft/winrt-rs/blob/d50b2d690700270c6f4138ee0b085c9b8a686306/crates/gen/src/types/futures.rs this could be placed on the stack, in other cases it could be allocated as part of a structure.

**Comment by kennykerr** [comment]
Yes, this would be simpler but there's the question of whether to support the creation of binaries that will load on Windows 7. Today, `winrt-rs` supports that but in future we may use Windows 8 as the min-supported version and we'll be able to use `WaitOnAddress` and friends.
