### ISSUE TITLE
ClickOnce deployment

### ISSUE THREAD

**Issue by ctaggart** [microsoft/winrt-rs#372]
It would be amazing to showcase an example that was a ClickOnce deployment.

Kusto Explorer is an application that uses ClickOnce deployment:
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-explorer

ClickOnce security and deployment
https://docs.microsoft.com/en-us/visualstudio/deployment/clickonce-security-and-deployment?view=vs-2019

ClickOnce Deployment for Visual C++ Applications
https://docs.microsoft.com/en-us/cpp/windows/clickonce-deployment-for-visual-cpp-applications?view=msvc-160

**Comment by kennykerr** [comment]
That would be great. I have no idea how to do that, but if you'd like to put together the simplest possible example I'd be happy to add it to [this repo's examples](https://github.com/microsoft/winrt-rs/tree/master/examples/) folder.

**Comment by ctaggart** [comment]
@kennykerr, any chance that you could add a simplest possible WinUI example first? Then I could see about wrapping it with a ClickOnce.

**Comment by kennykerr** [comment]
Sure!

**Comment by kennykerr** [comment]
Feel free to reopen if there's interest in exploring this further.
