### ISSUE TITLE
Incorrect usage of winrt::Waiter in generated impls for IAsync{Action,Operation}{WithProgress,} interfaces

### ISSUE THREAD

**Issue by Enigmatrix** [microsoft/winrt-rs#373]
Looking at the [macro for generating `.get()` for the IAsync\{Action,Operation\}\{WithProgress,\} interfaces](https://github.com/microsoft/winrt-rs/blob/a3eae9e1454de33e6ea55389bd0eb59fd587ee96/crates/gen/src/futures.rs#L44), we can see that we use the [winrt::Waker](https://github.com/microsoft/winrt-rs/blob/a3eae9e1454de33e6ea55389bd0eb59fd587ee96/src/runtime/waiter.rs) struct to wait for completion to occur before getting the result.  However, instead of waiting for the [unnamed Event](https://github.com/microsoft/winrt-rs/blob/a3eae9e1454de33e6ea55389bd0eb59fd587ee96/src/runtime/waiter.rs#L9) created by `winrt::Waiter` via the [impl of the Drop trait](https://github.com/microsoft/winrt-rs/blob/a3eae9e1454de33e6ea55389bd0eb59fd587ee96/src/runtime/waiter.rs#L25), the waiter actually moves it to the completion closure, making the waiting to occur in the completion handler instead of the thread that created the waiter itself, which leads to a call to `.get_results()` before completion occurs!
``` rust
pub fn get(&self) -> ::winrt::Result<#return_type> {
    if self.status()? == ::winrt::foundation::AsyncStatus::Started {
        let waiter = ::winrt::Waiter::new();
        self.set_completed(::winrt::foundation:: #handler::new(move |_sender, _args| { // <--- waiter moved here!
             waiter.signal();
             Ok(())
             // ... and waiter gets Drop-ed here, where there is no point in the WaitForSingleObject!
        }))?;
        // If the below code was uncommented to show the intended code, it would error out
        // due to the `move` above.  The `move` is required to satisfy lifetime constraints pertaining
        // to the use of `waiter` in the completion handler before this scope is exited. Rust doesn't know
        // that we are waiting for the handler to fire first, so it assumes that it is possible to exit the
        // scope first and leave a dangling reference!
       
       // drop(waiter) < --- will error out
    }
    self.get_results()
}
```

As a workaround, I made this function and called it instead using the generated `.get()` method (temporarily):
``` rust
fn wait_complete<T: ::winrt::RuntimeType, R: ::winrt::RuntimeType>(op: windows::foundation::IAsyncOperationWithProgress<T, R>) -> ::winrt::Result<T> {
    if op.status()? == ::winrt::foundation::AsyncStatus::Started {
        let (sender,recver) = std::sync::mpsc::sync_channel(1);
        op.set_completed(::winrt::foundation::AsyncOperationWithProgressCompletedHandler::new(move |_sender, _args| {
            sender.send(());
            Ok(())
        }))?;
        recver.recv().unwrap();
    }
    op.get_results()
}
```

The solution would be similar to the use of channels as above, by splitting `Waiter` into 2: a `Waiter` and `Signaller`. Example code is as below, based on the existing Waiter code (please note that this is untested and I am running on adrenaline 🐵):
``` rust
use crate::*;

/// A simple blocking waiter used by the generated bindings and should not generally be used directly.
pub struct Waiter(RawPtr);
pub struct Signaller(RawPtr);

impl Waiter {
    pub fn new() -> (Waiter, Signaller) {
        unsafe {
            let ev = CreateEventW(
                std::ptr::null_mut(),
                1,
                0,
                std::ptr::null_mut(),
            );
            (Waiter(ev), Signaller(ev))
        }
    }
}

impl Signaller {
    pub fn signal(&self) {
        unsafe {
            SetEvent(self.0);
        }
    }
}

impl Drop for Waiter {
    fn drop(&mut self) {
        unsafe {
            WaitForSingleObject(self.0, 0xFFFFFFFF);
            CloseHandle(self.0);
        }
    }
}

#[link(name = "kernel32")]
extern "system" {
    fn CreateEventW(security: RawPtr, manual: i32, state: i32, name: RawPtr) -> RawPtr;
    fn SetEvent(handle: RawPtr) -> i32;
    fn WaitForSingleObject(handle: RawPtr, milliseconds: u32) -> u32;
    fn CloseHandle(handle: RawPtr) -> i32;
}
```

Code generated from `gen_async_kind` will have to be modified as such:
``` rust
pub fn get(&self) -> ::winrt::Result<#return_type> {
    if self.status()? == ::winrt::foundation::AsyncStatus::Started {
        let (waiter, signaller) = ::winrt::Waiter::new();
        self.set_completed(::winrt::foundation:: #handler::new(move |_sender, _args| {
            signaller.signal();
            Ok(())
        }))?;
        // waiter gets dropped here, which means it waits for singaller to `.signal()`
    }
    self.get_results()
}
```

**Comment by kennykerr** [comment]
Good catch - and thanks for sharing a great repro! I assumed the closure would capture a reference as it does in C++ and that the waiter would still be dropped in the outer function.

**Comment by kennykerr** [comment]
Here's a fix: https://github.com/microsoft/winrt-rs/pull/374 

It's basically what you suggested - just making it explicit that it is unsafe. Ideally we could [use WaitOnAddress](https://github.com/microsoft/winrt-rs/issues/371) as @smj389 suggested. Maybe one day soon...
