### ISSUE TITLE
new build scheme without "cargo winrt" command doesn't work when winrt bindings is placed to subcrate

### ISSUE THREAD

**Issue by milyin** [microsoft/winrt-rs#377]
I tried to modify project https://github.com/kennykerr/win2d-rs to move winrt dependency to subcrate 'bindings' in order to accelerate build time, like it's implemented in https://github.com/robmikh/minesweeper-rs project.

The test project is https://github.com/milyin/win2d-rs

I found that it doesn't work because in this configuration .dll files from ".windows" directory are not copied to "target" directory:

```
   Compiling bindings v0.1.0 (C:\TEMP\win2d-rs\bindings)
   Compiling win2d-rs v0.1.0 (C:\TEMP\win2d-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 0.90s
     Running `target\debug\win2d-rs.exe`
thread 'main' panicked at 'Failed to create CanvasDevice: Error { code: 0x80040154, message: "Class not registered" }', src\main.rs:4:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\win2d-rs.exe` (exit code: 101)
```

**Comment by kennykerr** [comment]
Hmm... That should work. Will take a look asap. Thanks for the repro!

**Comment by milyin** [comment]
I've almost done the fix, will send request in a hour
