### ISSUE TITLE
simplest possible WinUI example

### ISSUE THREAD

**Issue by ctaggart** [microsoft/winrt-rs#384]
From #372, please add a simplest possible WinUI example.

**Comment by kennykerr** [comment]
Will do, sorry for the delay. Been kinda swamped. 😉

**Comment by kennykerr** [comment]
Hmm.. looking at the ClickOnce docs it seems you just need a desktop app. That's easy enough, but getting WinUI/Xaml running in a desktop app is not what I'd call simple (in any language). But it doesn't look like ClickOnce specifically needs Xaml so you may want to start with https://github.com/robmikh/minesweeper-rs but again not really all that simple. I'm working on a major update that should simplify this bootstrapping considerably but that will likely take another few weeks to land.

**Comment by allan2** [comment]
When the [WinUI 3 example at ProjectReunion](https://github.com/microsoft/ProjectReunion/issues/866) is working, could we add it to the examples here?

**Comment by kennykerr** [comment]
Yes @riverar was working on an example in his free time.
