### ISSUE TITLE
Default OS metadata

### ISSUE THREAD

**Issue by kennykerr** [microsoft/winrt-rs#394]
The `build` macro looks for a `.windows` folder in the root of your crate's workspace for any and all metadata. That's where you can place any metadata for OS and 3rd party APIs. It might be a good idea to include the metadata for all OS APIs with `winrt-rs` directly and only require `.windows` for 3rd party APIs. That would certainly make it easier for developers who only want to use OS APIs.

**Comment by iainnicol** [comment]
Wait, did you just add support for the entirety of win32, to this binding generator that was WinRT and WinMD focused? That was entirely unexpected but cool.

**Comment by kennykerr** [comment]
Yes, the `windows` crate now supports the entire Windows API. 😉 

https://kennykerr.ca/2021/01/21/rust-for-windows/
