### ISSUE TITLE
Need to model WinRT enums as structs

### ISSUE THREAD

**Issue by kennykerr** [microsoft/winrt-rs#65]
While it would be preferable use Rust enums, their variants are required to be unique and WinRT's enumerators are not guaranteed to be unique. Using structs would also allow flag/unsigned WinRT enums to provide bitmask operators. Something like this:

```Rust
#[derive(PartialEq, Eq)]
struct AsyncStatus {
    value: i32,
}

impl AsyncStatus {
    pub const Canceled: AsyncStatus = AsyncStatus { value: 2 };
    pub const Completed: AsyncStatus = AsyncStatus { value: 1 };
    pub const Error: AsyncStatus = AsyncStatus { value: 3 };
    pub const Started: AsyncStatus = AsyncStatus { value: 0 };
}
```

**Comment by jcotton42** [comment]
[bitflags](https://crates.io/crates/bitflags) may be appropriate here

**Comment by mqudsi** [comment]
It’s really quite unfortunate that rust-the-language doesn’t have a usable bitwise flags answer yet. I bump into this a lot writing embedded rust, and yes, the bitflags crate is a godsend.
