### ISSUE TITLE
Type Safety of ABI 

### ISSUE THREAD

**Issue by rylev** [microsoft/winrt-rs#75]
Currently there is very little type safety at the ABI layer. Mistakes in code generation around ABI are likely to not be caught until code is run, although these changes _should_ be easy to catch with the simple "smoke tests" already present. How big of a deal is this?

### Specifics

WinRT interfaces are conceptually simple wrappers around pointers to their VTables. However, we are currently encoding them as wrappers around a pointer to IUnknown.

For example, given an interface `IMyInterface`, there will be a struct defined as follows:
```rust
struct IMyInterface {
  ptr: ::winrt::IUnknown,
}
```
An arguably more correct implementation would wrap some sort of smart pointer to the VTable directly. 

```rust
ComPtr<abi_IMyInterface>

// comptr.rs
#[repr(transparent)
#[derive(Default)]
ComPtr<T>( *mut *mut T); // We could also constrain `T` to types that implement some unsafe interface like `ComVTable`

impl<T> ComPtr<T> {
  #[inline]
  fn as_raw() -> *mut *mut T {
    self.0
  }
}

/// Additional functionality to make this a ref counter pointer 
```

Additionally, the "this" pointer for ABI function calls is usually defined as `RawPointer` aka `*mut c_void`. It would be more correct for this to take a `ComPtr<abi_IMyInterface>` instead. In fact, this is true for all the arguments to the ABI functions, not just `this`.

**Comment by roblabla** [comment]
This was fixed by https://github.com/microsoft/winrt-rs/pull/97
