### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by rylev** [microsoft/winrt-rs#76]
Before we publish, we need to decide who is owner of the crate.

**Comment by Boddlnagg** [comment]
As one of the owners of https://crates.io/crates/winrt, I think we can discuss whether you want to take over that crate name. From my perspective it makes no sense to develop two Rust language projections for WinRT in parallel (and also I don't have time to maintain https://github.com/contextfree/winrt-rust in a meaningful sense any longer).

I'm really happy that there is now an alternative that is supported by Microsoft directly 👍

**Comment by kennykerr** [comment]
Thanks Patrick, that would be ideal.

**Comment by dns2utf8** [comment]
I would prefere if you could continue with the semver schema and release this project as `0.7.0`.

**Comment by Boddlnagg** [comment]
I agree that it would be necessary to release the first version as `0.7.0` to be semver-compatible. And `7` looks almost like `1`, doesn't it? 😉

**Comment by contextfree** [comment]
Yeah, having this project take over the winrt crate name would definitely be fine.
