### ISSUE TITLE
Provide richer error information via Result<T>

### ISSUE THREAD

**Issue by kennykerr** [microsoft/winrt-rs#89]
`winrt::Error` needs to encapsulate an `IRestrictedErrorInfo` in the same way that C++/WinRT's `winrt::hresult_error` exception type carries the error information from the call site for safe propagation and chaining and to provide richer error information for debugging.

**Comment by Alovchin91** [comment]
This looks like a low-hanging fruit I could pick up. Do you accept 3rd party contributions? What's the process? Can we discuss the scope?

**Comment by kennykerr** [comment]
We do accept contributions. There's some information about contributing here:

https://github.com/microsoft/winrt-rs/wiki/Contributing

WinRT error propagation is rather complex. It may be easier for me to handle this unless you're already very familiar with how WinRT restricted error objects work and how error information is propagated across the ABI boundaries. Regardless, I'll throw some notes here so we can begin the process of documenting this behavior.

Does that sound reasonable?

**Comment by Alovchin91** [comment]
Yep, sounds reasonable 👍 It would be nice to see some notes about how this works regardless.

Maybe I could also take a look at C++/WinRT implementation (and C#/WinRT eventually), unless this is really complicated and high-priority at the same time.
