### ISSUE TITLE
Import macro must support 3rd party dependencies

### ISSUE THREAD

**Issue by kennykerr** [microsoft/winrt-rs#93]
Dependencies include:

* Specific Windows SDK (such as [this package](https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts))
* Specific WinRT component (such as [Win2D](https://www.nuget.org/packages/Win2D.uwp))

Except for the SDK, WinRT components will include both metadata (winmd files) and executable binaries (DLL files) and most WinRT components are already distributed via nuget so perhaps the `winrt::import` macro needs to know how to unpack them directly.

**Comment by rylev** [comment]
Talking with @kennykerr about this, this is our plan for action:
* The `import!` macro will not do any network requests.

For nuget:
* We'll add a `nuget_dependencies` key to the Cargo.toml [manifest section)(https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table). 
* Create a tool `cargo-nuget` which can read that section and store it in a well known place. 
* The `import!` macro can then read nuget dependencies from that well known place.

**Comment by Jack-Works** [comment]
Is it possible to import type for `Microsoft.Update.Session`?

**Comment by chuckries** [comment]
@rylev @kennykerr it looks like the impl of this has changed since #118 was merged and this doesn't appear to be doc'd anywhere. Is there currently support for generating bindings for 3rd party winmd's? Trying to pull in Win2D.

**Comment by robmikh** [comment]
You'll need to place the winmd files you wish to generate bindings for in the `.winmd/winmd` folder. You'll also have to place the binaries in the `.winmd/[arch]` folder (e.g. `.winmd/x64`). In addition, you'll need to place the appropriate binaries from the [Microsoft.VCRTForwarders.140 nuget package]() in that folder as well. From there, just include the desired namespaces/types in your `windows::build!` macro.

Checkout Kenny's [Win2D sample](https://github.com/kennykerr/win2d-rs) as a guide.

**Comment by kennykerr** [comment]
I've added Win2D to the samples repo: https://github.com/kennykerr/samples-rs

Note that the `windows` crate first attempts to load metadata from the `.windows/winmd` folder, that Robert mentioned. Only if no winmd files are found will it fall back to the [default metadata](https://github.com/microsoft/windows-rs/tree/master/crates/winmd/default).
